// Code generated by ent, DO NOT EDIT.

package finalreport

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/openclarion/openclarion/internal/persistence/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldLTE(FieldID, id))
}

// CorrelationKey applies equality check predicate on the "correlation_key" field. It's identical to CorrelationKeyEQ.
func CorrelationKey(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEQ(FieldCorrelationKey, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEQ(FieldIdempotencyKey, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEQ(FieldTitle, v))
}

// ExecutiveSummary applies equality check predicate on the "executive_summary" field. It's identical to ExecutiveSummaryEQ.
func ExecutiveSummary(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEQ(FieldExecutiveSummary, v))
}

// Severity applies equality check predicate on the "severity" field. It's identical to SeverityEQ.
func Severity(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEQ(FieldSeverity, v))
}

// Confidence applies equality check predicate on the "confidence" field. It's identical to ConfidenceEQ.
func Confidence(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEQ(FieldConfidence, v))
}

// NotificationText applies equality check predicate on the "notification_text" field. It's identical to NotificationTextEQ.
func NotificationText(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEQ(FieldNotificationText, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEQ(FieldModel, v))
}

// OutputMode applies equality check predicate on the "output_mode" field. It's identical to OutputModeEQ.
func OutputMode(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEQ(FieldOutputMode, v))
}

// CreatedByWorkflow applies equality check predicate on the "created_by_workflow" field. It's identical to CreatedByWorkflowEQ.
func CreatedByWorkflow(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEQ(FieldCreatedByWorkflow, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEQ(FieldCreatedAt, v))
}

// CorrelationKeyEQ applies the EQ predicate on the "correlation_key" field.
func CorrelationKeyEQ(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEQ(FieldCorrelationKey, v))
}

// CorrelationKeyNEQ applies the NEQ predicate on the "correlation_key" field.
func CorrelationKeyNEQ(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNEQ(FieldCorrelationKey, v))
}

// CorrelationKeyIn applies the In predicate on the "correlation_key" field.
func CorrelationKeyIn(vs ...string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldIn(FieldCorrelationKey, vs...))
}

// CorrelationKeyNotIn applies the NotIn predicate on the "correlation_key" field.
func CorrelationKeyNotIn(vs ...string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNotIn(FieldCorrelationKey, vs...))
}

// CorrelationKeyGT applies the GT predicate on the "correlation_key" field.
func CorrelationKeyGT(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldGT(FieldCorrelationKey, v))
}

// CorrelationKeyGTE applies the GTE predicate on the "correlation_key" field.
func CorrelationKeyGTE(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldGTE(FieldCorrelationKey, v))
}

// CorrelationKeyLT applies the LT predicate on the "correlation_key" field.
func CorrelationKeyLT(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldLT(FieldCorrelationKey, v))
}

// CorrelationKeyLTE applies the LTE predicate on the "correlation_key" field.
func CorrelationKeyLTE(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldLTE(FieldCorrelationKey, v))
}

// CorrelationKeyContains applies the Contains predicate on the "correlation_key" field.
func CorrelationKeyContains(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldContains(FieldCorrelationKey, v))
}

// CorrelationKeyHasPrefix applies the HasPrefix predicate on the "correlation_key" field.
func CorrelationKeyHasPrefix(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldHasPrefix(FieldCorrelationKey, v))
}

// CorrelationKeyHasSuffix applies the HasSuffix predicate on the "correlation_key" field.
func CorrelationKeyHasSuffix(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldHasSuffix(FieldCorrelationKey, v))
}

// CorrelationKeyEqualFold applies the EqualFold predicate on the "correlation_key" field.
func CorrelationKeyEqualFold(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEqualFold(FieldCorrelationKey, v))
}

// CorrelationKeyContainsFold applies the ContainsFold predicate on the "correlation_key" field.
func CorrelationKeyContainsFold(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldContainsFold(FieldCorrelationKey, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldContainsFold(FieldTitle, v))
}

// ExecutiveSummaryEQ applies the EQ predicate on the "executive_summary" field.
func ExecutiveSummaryEQ(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEQ(FieldExecutiveSummary, v))
}

// ExecutiveSummaryNEQ applies the NEQ predicate on the "executive_summary" field.
func ExecutiveSummaryNEQ(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNEQ(FieldExecutiveSummary, v))
}

// ExecutiveSummaryIn applies the In predicate on the "executive_summary" field.
func ExecutiveSummaryIn(vs ...string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldIn(FieldExecutiveSummary, vs...))
}

// ExecutiveSummaryNotIn applies the NotIn predicate on the "executive_summary" field.
func ExecutiveSummaryNotIn(vs ...string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNotIn(FieldExecutiveSummary, vs...))
}

// ExecutiveSummaryGT applies the GT predicate on the "executive_summary" field.
func ExecutiveSummaryGT(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldGT(FieldExecutiveSummary, v))
}

// ExecutiveSummaryGTE applies the GTE predicate on the "executive_summary" field.
func ExecutiveSummaryGTE(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldGTE(FieldExecutiveSummary, v))
}

// ExecutiveSummaryLT applies the LT predicate on the "executive_summary" field.
func ExecutiveSummaryLT(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldLT(FieldExecutiveSummary, v))
}

// ExecutiveSummaryLTE applies the LTE predicate on the "executive_summary" field.
func ExecutiveSummaryLTE(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldLTE(FieldExecutiveSummary, v))
}

// ExecutiveSummaryContains applies the Contains predicate on the "executive_summary" field.
func ExecutiveSummaryContains(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldContains(FieldExecutiveSummary, v))
}

// ExecutiveSummaryHasPrefix applies the HasPrefix predicate on the "executive_summary" field.
func ExecutiveSummaryHasPrefix(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldHasPrefix(FieldExecutiveSummary, v))
}

// ExecutiveSummaryHasSuffix applies the HasSuffix predicate on the "executive_summary" field.
func ExecutiveSummaryHasSuffix(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldHasSuffix(FieldExecutiveSummary, v))
}

// ExecutiveSummaryEqualFold applies the EqualFold predicate on the "executive_summary" field.
func ExecutiveSummaryEqualFold(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEqualFold(FieldExecutiveSummary, v))
}

// ExecutiveSummaryContainsFold applies the ContainsFold predicate on the "executive_summary" field.
func ExecutiveSummaryContainsFold(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldContainsFold(FieldExecutiveSummary, v))
}

// SeverityEQ applies the EQ predicate on the "severity" field.
func SeverityEQ(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEQ(FieldSeverity, v))
}

// SeverityNEQ applies the NEQ predicate on the "severity" field.
func SeverityNEQ(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNEQ(FieldSeverity, v))
}

// SeverityIn applies the In predicate on the "severity" field.
func SeverityIn(vs ...string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldIn(FieldSeverity, vs...))
}

// SeverityNotIn applies the NotIn predicate on the "severity" field.
func SeverityNotIn(vs ...string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNotIn(FieldSeverity, vs...))
}

// SeverityGT applies the GT predicate on the "severity" field.
func SeverityGT(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldGT(FieldSeverity, v))
}

// SeverityGTE applies the GTE predicate on the "severity" field.
func SeverityGTE(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldGTE(FieldSeverity, v))
}

// SeverityLT applies the LT predicate on the "severity" field.
func SeverityLT(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldLT(FieldSeverity, v))
}

// SeverityLTE applies the LTE predicate on the "severity" field.
func SeverityLTE(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldLTE(FieldSeverity, v))
}

// SeverityContains applies the Contains predicate on the "severity" field.
func SeverityContains(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldContains(FieldSeverity, v))
}

// SeverityHasPrefix applies the HasPrefix predicate on the "severity" field.
func SeverityHasPrefix(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldHasPrefix(FieldSeverity, v))
}

// SeverityHasSuffix applies the HasSuffix predicate on the "severity" field.
func SeverityHasSuffix(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldHasSuffix(FieldSeverity, v))
}

// SeverityEqualFold applies the EqualFold predicate on the "severity" field.
func SeverityEqualFold(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEqualFold(FieldSeverity, v))
}

// SeverityContainsFold applies the ContainsFold predicate on the "severity" field.
func SeverityContainsFold(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldContainsFold(FieldSeverity, v))
}

// ConfidenceEQ applies the EQ predicate on the "confidence" field.
func ConfidenceEQ(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEQ(FieldConfidence, v))
}

// ConfidenceNEQ applies the NEQ predicate on the "confidence" field.
func ConfidenceNEQ(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNEQ(FieldConfidence, v))
}

// ConfidenceIn applies the In predicate on the "confidence" field.
func ConfidenceIn(vs ...string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldIn(FieldConfidence, vs...))
}

// ConfidenceNotIn applies the NotIn predicate on the "confidence" field.
func ConfidenceNotIn(vs ...string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNotIn(FieldConfidence, vs...))
}

// ConfidenceGT applies the GT predicate on the "confidence" field.
func ConfidenceGT(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldGT(FieldConfidence, v))
}

// ConfidenceGTE applies the GTE predicate on the "confidence" field.
func ConfidenceGTE(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldGTE(FieldConfidence, v))
}

// ConfidenceLT applies the LT predicate on the "confidence" field.
func ConfidenceLT(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldLT(FieldConfidence, v))
}

// ConfidenceLTE applies the LTE predicate on the "confidence" field.
func ConfidenceLTE(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldLTE(FieldConfidence, v))
}

// ConfidenceContains applies the Contains predicate on the "confidence" field.
func ConfidenceContains(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldContains(FieldConfidence, v))
}

// ConfidenceHasPrefix applies the HasPrefix predicate on the "confidence" field.
func ConfidenceHasPrefix(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldHasPrefix(FieldConfidence, v))
}

// ConfidenceHasSuffix applies the HasSuffix predicate on the "confidence" field.
func ConfidenceHasSuffix(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldHasSuffix(FieldConfidence, v))
}

// ConfidenceEqualFold applies the EqualFold predicate on the "confidence" field.
func ConfidenceEqualFold(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEqualFold(FieldConfidence, v))
}

// ConfidenceContainsFold applies the ContainsFold predicate on the "confidence" field.
func ConfidenceContainsFold(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldContainsFold(FieldConfidence, v))
}

// NotificationTextEQ applies the EQ predicate on the "notification_text" field.
func NotificationTextEQ(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEQ(FieldNotificationText, v))
}

// NotificationTextNEQ applies the NEQ predicate on the "notification_text" field.
func NotificationTextNEQ(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNEQ(FieldNotificationText, v))
}

// NotificationTextIn applies the In predicate on the "notification_text" field.
func NotificationTextIn(vs ...string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldIn(FieldNotificationText, vs...))
}

// NotificationTextNotIn applies the NotIn predicate on the "notification_text" field.
func NotificationTextNotIn(vs ...string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNotIn(FieldNotificationText, vs...))
}

// NotificationTextGT applies the GT predicate on the "notification_text" field.
func NotificationTextGT(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldGT(FieldNotificationText, v))
}

// NotificationTextGTE applies the GTE predicate on the "notification_text" field.
func NotificationTextGTE(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldGTE(FieldNotificationText, v))
}

// NotificationTextLT applies the LT predicate on the "notification_text" field.
func NotificationTextLT(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldLT(FieldNotificationText, v))
}

// NotificationTextLTE applies the LTE predicate on the "notification_text" field.
func NotificationTextLTE(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldLTE(FieldNotificationText, v))
}

// NotificationTextContains applies the Contains predicate on the "notification_text" field.
func NotificationTextContains(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldContains(FieldNotificationText, v))
}

// NotificationTextHasPrefix applies the HasPrefix predicate on the "notification_text" field.
func NotificationTextHasPrefix(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldHasPrefix(FieldNotificationText, v))
}

// NotificationTextHasSuffix applies the HasSuffix predicate on the "notification_text" field.
func NotificationTextHasSuffix(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldHasSuffix(FieldNotificationText, v))
}

// NotificationTextEqualFold applies the EqualFold predicate on the "notification_text" field.
func NotificationTextEqualFold(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEqualFold(FieldNotificationText, v))
}

// NotificationTextContainsFold applies the ContainsFold predicate on the "notification_text" field.
func NotificationTextContainsFold(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldContainsFold(FieldNotificationText, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldHasSuffix(FieldModel, v))
}

// ModelIsNil applies the IsNil predicate on the "model" field.
func ModelIsNil() predicate.FinalReport {
	return predicate.FinalReport(sql.FieldIsNull(FieldModel))
}

// ModelNotNil applies the NotNil predicate on the "model" field.
func ModelNotNil() predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNotNull(FieldModel))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldContainsFold(FieldModel, v))
}

// OutputModeEQ applies the EQ predicate on the "output_mode" field.
func OutputModeEQ(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEQ(FieldOutputMode, v))
}

// OutputModeNEQ applies the NEQ predicate on the "output_mode" field.
func OutputModeNEQ(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNEQ(FieldOutputMode, v))
}

// OutputModeIn applies the In predicate on the "output_mode" field.
func OutputModeIn(vs ...string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldIn(FieldOutputMode, vs...))
}

// OutputModeNotIn applies the NotIn predicate on the "output_mode" field.
func OutputModeNotIn(vs ...string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNotIn(FieldOutputMode, vs...))
}

// OutputModeGT applies the GT predicate on the "output_mode" field.
func OutputModeGT(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldGT(FieldOutputMode, v))
}

// OutputModeGTE applies the GTE predicate on the "output_mode" field.
func OutputModeGTE(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldGTE(FieldOutputMode, v))
}

// OutputModeLT applies the LT predicate on the "output_mode" field.
func OutputModeLT(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldLT(FieldOutputMode, v))
}

// OutputModeLTE applies the LTE predicate on the "output_mode" field.
func OutputModeLTE(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldLTE(FieldOutputMode, v))
}

// OutputModeContains applies the Contains predicate on the "output_mode" field.
func OutputModeContains(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldContains(FieldOutputMode, v))
}

// OutputModeHasPrefix applies the HasPrefix predicate on the "output_mode" field.
func OutputModeHasPrefix(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldHasPrefix(FieldOutputMode, v))
}

// OutputModeHasSuffix applies the HasSuffix predicate on the "output_mode" field.
func OutputModeHasSuffix(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldHasSuffix(FieldOutputMode, v))
}

// OutputModeIsNil applies the IsNil predicate on the "output_mode" field.
func OutputModeIsNil() predicate.FinalReport {
	return predicate.FinalReport(sql.FieldIsNull(FieldOutputMode))
}

// OutputModeNotNil applies the NotNil predicate on the "output_mode" field.
func OutputModeNotNil() predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNotNull(FieldOutputMode))
}

// OutputModeEqualFold applies the EqualFold predicate on the "output_mode" field.
func OutputModeEqualFold(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEqualFold(FieldOutputMode, v))
}

// OutputModeContainsFold applies the ContainsFold predicate on the "output_mode" field.
func OutputModeContainsFold(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldContainsFold(FieldOutputMode, v))
}

// CreatedByWorkflowEQ applies the EQ predicate on the "created_by_workflow" field.
func CreatedByWorkflowEQ(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEQ(FieldCreatedByWorkflow, v))
}

// CreatedByWorkflowNEQ applies the NEQ predicate on the "created_by_workflow" field.
func CreatedByWorkflowNEQ(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNEQ(FieldCreatedByWorkflow, v))
}

// CreatedByWorkflowIn applies the In predicate on the "created_by_workflow" field.
func CreatedByWorkflowIn(vs ...string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldIn(FieldCreatedByWorkflow, vs...))
}

// CreatedByWorkflowNotIn applies the NotIn predicate on the "created_by_workflow" field.
func CreatedByWorkflowNotIn(vs ...string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNotIn(FieldCreatedByWorkflow, vs...))
}

// CreatedByWorkflowGT applies the GT predicate on the "created_by_workflow" field.
func CreatedByWorkflowGT(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldGT(FieldCreatedByWorkflow, v))
}

// CreatedByWorkflowGTE applies the GTE predicate on the "created_by_workflow" field.
func CreatedByWorkflowGTE(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldGTE(FieldCreatedByWorkflow, v))
}

// CreatedByWorkflowLT applies the LT predicate on the "created_by_workflow" field.
func CreatedByWorkflowLT(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldLT(FieldCreatedByWorkflow, v))
}

// CreatedByWorkflowLTE applies the LTE predicate on the "created_by_workflow" field.
func CreatedByWorkflowLTE(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldLTE(FieldCreatedByWorkflow, v))
}

// CreatedByWorkflowContains applies the Contains predicate on the "created_by_workflow" field.
func CreatedByWorkflowContains(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldContains(FieldCreatedByWorkflow, v))
}

// CreatedByWorkflowHasPrefix applies the HasPrefix predicate on the "created_by_workflow" field.
func CreatedByWorkflowHasPrefix(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldHasPrefix(FieldCreatedByWorkflow, v))
}

// CreatedByWorkflowHasSuffix applies the HasSuffix predicate on the "created_by_workflow" field.
func CreatedByWorkflowHasSuffix(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldHasSuffix(FieldCreatedByWorkflow, v))
}

// CreatedByWorkflowIsNil applies the IsNil predicate on the "created_by_workflow" field.
func CreatedByWorkflowIsNil() predicate.FinalReport {
	return predicate.FinalReport(sql.FieldIsNull(FieldCreatedByWorkflow))
}

// CreatedByWorkflowNotNil applies the NotNil predicate on the "created_by_workflow" field.
func CreatedByWorkflowNotNil() predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNotNull(FieldCreatedByWorkflow))
}

// CreatedByWorkflowEqualFold applies the EqualFold predicate on the "created_by_workflow" field.
func CreatedByWorkflowEqualFold(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEqualFold(FieldCreatedByWorkflow, v))
}

// CreatedByWorkflowContainsFold applies the ContainsFold predicate on the "created_by_workflow" field.
func CreatedByWorkflowContainsFold(v string) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldContainsFold(FieldCreatedByWorkflow, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FinalReport {
	return predicate.FinalReport(sql.FieldLTE(FieldCreatedAt, v))
}

// HasSubReports applies the HasEdge predicate on the "sub_reports" edge.
func HasSubReports() predicate.FinalReport {
	return predicate.FinalReport(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, SubReportsTable, SubReportsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubReportsWith applies the HasEdge predicate on the "sub_reports" edge with a given conditions (other predicates).
func HasSubReportsWith(preds ...predicate.SubReport) predicate.FinalReport {
	return predicate.FinalReport(func(s *sql.Selector) {
		step := newSubReportsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNotificationDeliveries applies the HasEdge predicate on the "notification_deliveries" edge.
func HasNotificationDeliveries() predicate.FinalReport {
	return predicate.FinalReport(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, NotificationDeliveriesTable, NotificationDeliveriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNotificationDeliveriesWith applies the HasEdge predicate on the "notification_deliveries" edge with a given conditions (other predicates).
func HasNotificationDeliveriesWith(preds ...predicate.ReportNotificationDelivery) predicate.FinalReport {
	return predicate.FinalReport(func(s *sql.Selector) {
		step := newNotificationDeliveriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FinalReport) predicate.FinalReport {
	return predicate.FinalReport(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FinalReport) predicate.FinalReport {
	return predicate.FinalReport(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FinalReport) predicate.FinalReport {
	return predicate.FinalReport(sql.NotPredicates(p))
}
