// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AlertEvent is the predicate function for alertevent builders.
type AlertEvent func(*sql.Selector)

// AlertGroup is the predicate function for alertgroup builders.
type AlertGroup func(*sql.Selector)

// AlertSourceProfile is the predicate function for alertsourceprofile builders.
type AlertSourceProfile func(*sql.Selector)

// ChatSession is the predicate function for chatsession builders.
type ChatSession func(*sql.Selector)

// ChatTurn is the predicate function for chatturn builders.
type ChatTurn func(*sql.Selector)

// DiagnosisAuthTicket is the predicate function for diagnosisauthticket builders.
type DiagnosisAuthTicket func(*sql.Selector)

// DiagnosisTask is the predicate function for diagnosistask builders.
type DiagnosisTask func(*sql.Selector)

// DiagnosisTaskEvent is the predicate function for diagnosistaskevent builders.
type DiagnosisTaskEvent func(*sql.Selector)

// DiagnosisToolTemplate is the predicate function for diagnosistooltemplate builders.
type DiagnosisToolTemplate func(*sql.Selector)

// DirectoryDepartment is the predicate function for directorydepartment builders.
type DirectoryDepartment func(*sql.Selector)

// DirectorySyncRun is the predicate function for directorysyncrun builders.
type DirectorySyncRun func(*sql.Selector)

// DirectoryUser is the predicate function for directoryuser builders.
type DirectoryUser func(*sql.Selector)

// EvidenceSnapshot is the predicate function for evidencesnapshot builders.
type EvidenceSnapshot func(*sql.Selector)

// FinalReport is the predicate function for finalreport builders.
type FinalReport func(*sql.Selector)

// GroupingPolicy is the predicate function for groupingpolicy builders.
type GroupingPolicy func(*sql.Selector)

// NotificationChannelProfile is the predicate function for notificationchannelprofile builders.
type NotificationChannelProfile func(*sql.Selector)

// NotificationChannelTestProof is the predicate function for notificationchanneltestproof builders.
type NotificationChannelTestProof func(*sql.Selector)

// RBACAssignment is the predicate function for rbacassignment builders.
type RBACAssignment func(*sql.Selector)

// ReportNotificationDelivery is the predicate function for reportnotificationdelivery builders.
type ReportNotificationDelivery func(*sql.Selector)

// ReportWorkflowPolicy is the predicate function for reportworkflowpolicy builders.
type ReportWorkflowPolicy func(*sql.Selector)

// ReportWorkflowSchedule is the predicate function for reportworkflowschedule builders.
type ReportWorkflowSchedule func(*sql.Selector)

// SubReport is the predicate function for subreport builders.
type SubReport func(*sql.Selector)
