// Code generated by ent, DO NOT EDIT.

package evidencesnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the evidencesnapshot type in the database.
	Label = "evidence_snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAlertGroupID holds the string denoting the alert_group_id field in the database.
	FieldAlertGroupID = "alert_group_id"
	// FieldDigest holds the string denoting the digest field in the database.
	FieldDigest = "digest"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldProvenance holds the string denoting the provenance field in the database.
	FieldProvenance = "provenance"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMissingFields holds the string denoting the missing_fields field in the database.
	FieldMissingFields = "missing_fields"
	// FieldCreatedByWorkflow holds the string denoting the created_by_workflow field in the database.
	FieldCreatedByWorkflow = "created_by_workflow"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// EdgeTasks holds the string denoting the tasks edge name in mutations.
	EdgeTasks = "tasks"
	// EdgeSubReports holds the string denoting the sub_reports edge name in mutations.
	EdgeSubReports = "sub_reports"
	// Table holds the table name of the evidencesnapshot in the database.
	Table = "evidence_snapshots"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "evidence_snapshots"
	// GroupInverseTable is the table name for the AlertGroup entity.
	// It exists in this package in order to avoid circular dependency with the "alertgroup" package.
	GroupInverseTable = "alert_groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "alert_group_id"
	// TasksTable is the table that holds the tasks relation/edge.
	TasksTable = "diagnosis_tasks"
	// TasksInverseTable is the table name for the DiagnosisTask entity.
	// It exists in this package in order to avoid circular dependency with the "diagnosistask" package.
	TasksInverseTable = "diagnosis_tasks"
	// TasksColumn is the table column denoting the tasks relation/edge.
	TasksColumn = "evidence_snapshot_id"
	// SubReportsTable is the table that holds the sub_reports relation/edge.
	SubReportsTable = "sub_reports"
	// SubReportsInverseTable is the table name for the SubReport entity.
	// It exists in this package in order to avoid circular dependency with the "subreport" package.
	SubReportsInverseTable = "sub_reports"
	// SubReportsColumn is the table column denoting the sub_reports relation/edge.
	SubReportsColumn = "evidence_snapshot_id"
)

// Columns holds all SQL columns for evidencesnapshot fields.
var Columns = []string{
	FieldID,
	FieldAlertGroupID,
	FieldDigest,
	FieldPayload,
	FieldProvenance,
	FieldStatus,
	FieldMissingFields,
	FieldCreatedByWorkflow,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DigestValidator is a validator for the "digest" field. It is called by the builders before save.
	DigestValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// CreatedByWorkflowValidator is a validator for the "created_by_workflow" field. It is called by the builders before save.
	CreatedByWorkflowValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the EvidenceSnapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAlertGroupID orders the results by the alert_group_id field.
func ByAlertGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlertGroupID, opts...).ToFunc()
}

// ByDigest orders the results by the digest field.
func ByDigest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDigest, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedByWorkflow orders the results by the created_by_workflow field.
func ByCreatedByWorkflow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedByWorkflow, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByTasksCount orders the results by tasks count.
func ByTasksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTasksStep(), opts...)
	}
}

// ByTasks orders the results by tasks terms.
func ByTasks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTasksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySubReportsCount orders the results by sub_reports count.
func BySubReportsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSubReportsStep(), opts...)
	}
}

// BySubReports orders the results by sub_reports terms.
func BySubReports(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubReportsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
func newTasksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TasksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TasksTable, TasksColumn),
	)
}
func newSubReportsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubReportsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SubReportsTable, SubReportsColumn),
	)
}
