// Code generated by ent, DO NOT EDIT.

package directorydepartment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/openclarion/openclarion/internal/persistence/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldTenantID, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldProvider, v))
}

// ExternalID applies equality check predicate on the "external_id" field. It's identical to ExternalIDEQ.
func ExternalID(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldExternalID, v))
}

// ParentExternalID applies equality check predicate on the "parent_external_id" field. It's identical to ParentExternalIDEQ.
func ParentExternalID(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldParentExternalID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldName, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldDisplayName, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldPath, v))
}

// ParentPath applies equality check predicate on the "parent_path" field. It's identical to ParentPathEQ.
func ParentPath(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldParentPath, v))
}

// Level applies equality check predicate on the "level" field. It's identical to LevelEQ.
func Level(v int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldLevel, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldSource, v))
}

// MemberCount applies equality check predicate on the "member_count" field. It's identical to MemberCountEQ.
func MemberCount(v int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldMemberCount, v))
}

// SourceUpdatedAt applies equality check predicate on the "source_updated_at" field. It's identical to SourceUpdatedAtEQ.
func SourceUpdatedAt(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldSourceUpdatedAt, v))
}

// SyncedAt applies equality check predicate on the "synced_at" field. It's identical to SyncedAtEQ.
func SyncedAt(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldSyncedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNotIn(FieldTenantID, vs...))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldContainsFold(FieldProvider, v))
}

// ExternalIDEQ applies the EQ predicate on the "external_id" field.
func ExternalIDEQ(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldExternalID, v))
}

// ExternalIDNEQ applies the NEQ predicate on the "external_id" field.
func ExternalIDNEQ(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNEQ(FieldExternalID, v))
}

// ExternalIDIn applies the In predicate on the "external_id" field.
func ExternalIDIn(vs ...string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldIn(FieldExternalID, vs...))
}

// ExternalIDNotIn applies the NotIn predicate on the "external_id" field.
func ExternalIDNotIn(vs ...string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNotIn(FieldExternalID, vs...))
}

// ExternalIDGT applies the GT predicate on the "external_id" field.
func ExternalIDGT(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGT(FieldExternalID, v))
}

// ExternalIDGTE applies the GTE predicate on the "external_id" field.
func ExternalIDGTE(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGTE(FieldExternalID, v))
}

// ExternalIDLT applies the LT predicate on the "external_id" field.
func ExternalIDLT(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLT(FieldExternalID, v))
}

// ExternalIDLTE applies the LTE predicate on the "external_id" field.
func ExternalIDLTE(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLTE(FieldExternalID, v))
}

// ExternalIDContains applies the Contains predicate on the "external_id" field.
func ExternalIDContains(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldContains(FieldExternalID, v))
}

// ExternalIDHasPrefix applies the HasPrefix predicate on the "external_id" field.
func ExternalIDHasPrefix(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldHasPrefix(FieldExternalID, v))
}

// ExternalIDHasSuffix applies the HasSuffix predicate on the "external_id" field.
func ExternalIDHasSuffix(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldHasSuffix(FieldExternalID, v))
}

// ExternalIDEqualFold applies the EqualFold predicate on the "external_id" field.
func ExternalIDEqualFold(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEqualFold(FieldExternalID, v))
}

// ExternalIDContainsFold applies the ContainsFold predicate on the "external_id" field.
func ExternalIDContainsFold(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldContainsFold(FieldExternalID, v))
}

// ParentExternalIDEQ applies the EQ predicate on the "parent_external_id" field.
func ParentExternalIDEQ(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldParentExternalID, v))
}

// ParentExternalIDNEQ applies the NEQ predicate on the "parent_external_id" field.
func ParentExternalIDNEQ(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNEQ(FieldParentExternalID, v))
}

// ParentExternalIDIn applies the In predicate on the "parent_external_id" field.
func ParentExternalIDIn(vs ...string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldIn(FieldParentExternalID, vs...))
}

// ParentExternalIDNotIn applies the NotIn predicate on the "parent_external_id" field.
func ParentExternalIDNotIn(vs ...string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNotIn(FieldParentExternalID, vs...))
}

// ParentExternalIDGT applies the GT predicate on the "parent_external_id" field.
func ParentExternalIDGT(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGT(FieldParentExternalID, v))
}

// ParentExternalIDGTE applies the GTE predicate on the "parent_external_id" field.
func ParentExternalIDGTE(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGTE(FieldParentExternalID, v))
}

// ParentExternalIDLT applies the LT predicate on the "parent_external_id" field.
func ParentExternalIDLT(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLT(FieldParentExternalID, v))
}

// ParentExternalIDLTE applies the LTE predicate on the "parent_external_id" field.
func ParentExternalIDLTE(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLTE(FieldParentExternalID, v))
}

// ParentExternalIDContains applies the Contains predicate on the "parent_external_id" field.
func ParentExternalIDContains(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldContains(FieldParentExternalID, v))
}

// ParentExternalIDHasPrefix applies the HasPrefix predicate on the "parent_external_id" field.
func ParentExternalIDHasPrefix(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldHasPrefix(FieldParentExternalID, v))
}

// ParentExternalIDHasSuffix applies the HasSuffix predicate on the "parent_external_id" field.
func ParentExternalIDHasSuffix(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldHasSuffix(FieldParentExternalID, v))
}

// ParentExternalIDIsNil applies the IsNil predicate on the "parent_external_id" field.
func ParentExternalIDIsNil() predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldIsNull(FieldParentExternalID))
}

// ParentExternalIDNotNil applies the NotNil predicate on the "parent_external_id" field.
func ParentExternalIDNotNil() predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNotNull(FieldParentExternalID))
}

// ParentExternalIDEqualFold applies the EqualFold predicate on the "parent_external_id" field.
func ParentExternalIDEqualFold(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEqualFold(FieldParentExternalID, v))
}

// ParentExternalIDContainsFold applies the ContainsFold predicate on the "parent_external_id" field.
func ParentExternalIDContainsFold(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldContainsFold(FieldParentExternalID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldContainsFold(FieldName, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldContainsFold(FieldDisplayName, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldContainsFold(FieldPath, v))
}

// ParentPathEQ applies the EQ predicate on the "parent_path" field.
func ParentPathEQ(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldParentPath, v))
}

// ParentPathNEQ applies the NEQ predicate on the "parent_path" field.
func ParentPathNEQ(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNEQ(FieldParentPath, v))
}

// ParentPathIn applies the In predicate on the "parent_path" field.
func ParentPathIn(vs ...string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldIn(FieldParentPath, vs...))
}

// ParentPathNotIn applies the NotIn predicate on the "parent_path" field.
func ParentPathNotIn(vs ...string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNotIn(FieldParentPath, vs...))
}

// ParentPathGT applies the GT predicate on the "parent_path" field.
func ParentPathGT(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGT(FieldParentPath, v))
}

// ParentPathGTE applies the GTE predicate on the "parent_path" field.
func ParentPathGTE(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGTE(FieldParentPath, v))
}

// ParentPathLT applies the LT predicate on the "parent_path" field.
func ParentPathLT(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLT(FieldParentPath, v))
}

// ParentPathLTE applies the LTE predicate on the "parent_path" field.
func ParentPathLTE(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLTE(FieldParentPath, v))
}

// ParentPathContains applies the Contains predicate on the "parent_path" field.
func ParentPathContains(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldContains(FieldParentPath, v))
}

// ParentPathHasPrefix applies the HasPrefix predicate on the "parent_path" field.
func ParentPathHasPrefix(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldHasPrefix(FieldParentPath, v))
}

// ParentPathHasSuffix applies the HasSuffix predicate on the "parent_path" field.
func ParentPathHasSuffix(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldHasSuffix(FieldParentPath, v))
}

// ParentPathIsNil applies the IsNil predicate on the "parent_path" field.
func ParentPathIsNil() predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldIsNull(FieldParentPath))
}

// ParentPathNotNil applies the NotNil predicate on the "parent_path" field.
func ParentPathNotNil() predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNotNull(FieldParentPath))
}

// ParentPathEqualFold applies the EqualFold predicate on the "parent_path" field.
func ParentPathEqualFold(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEqualFold(FieldParentPath, v))
}

// ParentPathContainsFold applies the ContainsFold predicate on the "parent_path" field.
func ParentPathContainsFold(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldContainsFold(FieldParentPath, v))
}

// LevelEQ applies the EQ predicate on the "level" field.
func LevelEQ(v int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldLevel, v))
}

// LevelNEQ applies the NEQ predicate on the "level" field.
func LevelNEQ(v int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNEQ(FieldLevel, v))
}

// LevelIn applies the In predicate on the "level" field.
func LevelIn(vs ...int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldIn(FieldLevel, vs...))
}

// LevelNotIn applies the NotIn predicate on the "level" field.
func LevelNotIn(vs ...int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNotIn(FieldLevel, vs...))
}

// LevelGT applies the GT predicate on the "level" field.
func LevelGT(v int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGT(FieldLevel, v))
}

// LevelGTE applies the GTE predicate on the "level" field.
func LevelGTE(v int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGTE(FieldLevel, v))
}

// LevelLT applies the LT predicate on the "level" field.
func LevelLT(v int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLT(FieldLevel, v))
}

// LevelLTE applies the LTE predicate on the "level" field.
func LevelLTE(v int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLTE(FieldLevel, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldHasSuffix(FieldSource, v))
}

// SourceIsNil applies the IsNil predicate on the "source" field.
func SourceIsNil() predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldIsNull(FieldSource))
}

// SourceNotNil applies the NotNil predicate on the "source" field.
func SourceNotNil() predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNotNull(FieldSource))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldContainsFold(FieldSource, v))
}

// MemberCountEQ applies the EQ predicate on the "member_count" field.
func MemberCountEQ(v int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldMemberCount, v))
}

// MemberCountNEQ applies the NEQ predicate on the "member_count" field.
func MemberCountNEQ(v int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNEQ(FieldMemberCount, v))
}

// MemberCountIn applies the In predicate on the "member_count" field.
func MemberCountIn(vs ...int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldIn(FieldMemberCount, vs...))
}

// MemberCountNotIn applies the NotIn predicate on the "member_count" field.
func MemberCountNotIn(vs ...int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNotIn(FieldMemberCount, vs...))
}

// MemberCountGT applies the GT predicate on the "member_count" field.
func MemberCountGT(v int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGT(FieldMemberCount, v))
}

// MemberCountGTE applies the GTE predicate on the "member_count" field.
func MemberCountGTE(v int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGTE(FieldMemberCount, v))
}

// MemberCountLT applies the LT predicate on the "member_count" field.
func MemberCountLT(v int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLT(FieldMemberCount, v))
}

// MemberCountLTE applies the LTE predicate on the "member_count" field.
func MemberCountLTE(v int) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLTE(FieldMemberCount, v))
}

// SourceUpdatedAtEQ applies the EQ predicate on the "source_updated_at" field.
func SourceUpdatedAtEQ(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldSourceUpdatedAt, v))
}

// SourceUpdatedAtNEQ applies the NEQ predicate on the "source_updated_at" field.
func SourceUpdatedAtNEQ(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNEQ(FieldSourceUpdatedAt, v))
}

// SourceUpdatedAtIn applies the In predicate on the "source_updated_at" field.
func SourceUpdatedAtIn(vs ...time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldIn(FieldSourceUpdatedAt, vs...))
}

// SourceUpdatedAtNotIn applies the NotIn predicate on the "source_updated_at" field.
func SourceUpdatedAtNotIn(vs ...time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNotIn(FieldSourceUpdatedAt, vs...))
}

// SourceUpdatedAtGT applies the GT predicate on the "source_updated_at" field.
func SourceUpdatedAtGT(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGT(FieldSourceUpdatedAt, v))
}

// SourceUpdatedAtGTE applies the GTE predicate on the "source_updated_at" field.
func SourceUpdatedAtGTE(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGTE(FieldSourceUpdatedAt, v))
}

// SourceUpdatedAtLT applies the LT predicate on the "source_updated_at" field.
func SourceUpdatedAtLT(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLT(FieldSourceUpdatedAt, v))
}

// SourceUpdatedAtLTE applies the LTE predicate on the "source_updated_at" field.
func SourceUpdatedAtLTE(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLTE(FieldSourceUpdatedAt, v))
}

// SourceUpdatedAtIsNil applies the IsNil predicate on the "source_updated_at" field.
func SourceUpdatedAtIsNil() predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldIsNull(FieldSourceUpdatedAt))
}

// SourceUpdatedAtNotNil applies the NotNil predicate on the "source_updated_at" field.
func SourceUpdatedAtNotNil() predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNotNull(FieldSourceUpdatedAt))
}

// SyncedAtEQ applies the EQ predicate on the "synced_at" field.
func SyncedAtEQ(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldSyncedAt, v))
}

// SyncedAtNEQ applies the NEQ predicate on the "synced_at" field.
func SyncedAtNEQ(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNEQ(FieldSyncedAt, v))
}

// SyncedAtIn applies the In predicate on the "synced_at" field.
func SyncedAtIn(vs ...time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldIn(FieldSyncedAt, vs...))
}

// SyncedAtNotIn applies the NotIn predicate on the "synced_at" field.
func SyncedAtNotIn(vs ...time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNotIn(FieldSyncedAt, vs...))
}

// SyncedAtGT applies the GT predicate on the "synced_at" field.
func SyncedAtGT(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGT(FieldSyncedAt, v))
}

// SyncedAtGTE applies the GTE predicate on the "synced_at" field.
func SyncedAtGTE(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGTE(FieldSyncedAt, v))
}

// SyncedAtLT applies the LT predicate on the "synced_at" field.
func SyncedAtLT(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLT(FieldSyncedAt, v))
}

// SyncedAtLTE applies the LTE predicate on the "synced_at" field.
func SyncedAtLTE(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLTE(FieldSyncedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DirectoryDepartment) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DirectoryDepartment) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DirectoryDepartment) predicate.DirectoryDepartment {
	return predicate.DirectoryDepartment(sql.NotPredicates(p))
}
