// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/openclarion/openclarion/internal/persistence/ent/alertevent"
)

// AlertEvent is the model entity for the AlertEvent schema.
type AlertEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// upstream provider identifier, e.g. "alertmanager", "datadog"
	Source string `json:"source,omitempty"`
	// optional operator-managed alert source profile that produced the event; 0 means unbound
	AlertSourceProfileID int `json:"alert_source_profile_id,omitempty"`
	// fingerprint reported by the upstream provider, retained verbatim
	SourceFingerprint string `json:"source_fingerprint,omitempty"`
	// sha256 hex of canonical(sorted(labels)); computed in-process
	CanonicalFingerprint string `json:"canonical_fingerprint,omitempty"`
	// alert labels, canonicalised before fingerprinting
	Labels map[string]string `json:"labels,omitempty"`
	// alert annotations (free-form descriptive metadata)
	Annotations map[string]string `json:"annotations,omitempty"`
	// raw upstream payload as JSONB; retained for forensic debugging only (per JSONB Usage rule in schema-catalog.md)
	RawPayload json.RawMessage `json:"raw_payload,omitempty"`
	// "firing" | "resolved"
	Status string `json:"status,omitempty"`
	// UTC, microsecond-truncated; part of the natural unique key
	StartsAt time.Time `json:"starts_at,omitempty"`
	// set when status transitions to resolved
	EndsAt *time.Time `json:"ends_at,omitempty"`
	// server-side ingestion timestamp
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AlertEventQuery when eager-loading is set.
	Edges        AlertEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AlertEventEdges holds the relations/edges for other nodes in the graph.
type AlertEventEdges struct {
	// Groups holds the value of the groups edge.
	Groups []*AlertGroup `json:"groups,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// GroupsOrErr returns the Groups value or an error if the edge
// was not loaded in eager-loading.
func (e AlertEventEdges) GroupsOrErr() ([]*AlertGroup, error) {
	if e.loadedTypes[0] {
		return e.Groups, nil
	}
	return nil, &NotLoadedError{edge: "groups"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AlertEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case alertevent.FieldLabels, alertevent.FieldAnnotations, alertevent.FieldRawPayload:
			values[i] = new([]byte)
		case alertevent.FieldID, alertevent.FieldAlertSourceProfileID:
			values[i] = new(sql.NullInt64)
		case alertevent.FieldSource, alertevent.FieldSourceFingerprint, alertevent.FieldCanonicalFingerprint, alertevent.FieldStatus:
			values[i] = new(sql.NullString)
		case alertevent.FieldStartsAt, alertevent.FieldEndsAt, alertevent.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AlertEvent fields.
func (_m *AlertEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case alertevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case alertevent.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case alertevent.FieldAlertSourceProfileID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field alert_source_profile_id", values[i])
			} else if value.Valid {
				_m.AlertSourceProfileID = int(value.Int64)
			}
		case alertevent.FieldSourceFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_fingerprint", values[i])
			} else if value.Valid {
				_m.SourceFingerprint = value.String
			}
		case alertevent.FieldCanonicalFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field canonical_fingerprint", values[i])
			} else if value.Valid {
				_m.CanonicalFingerprint = value.String
			}
		case alertevent.FieldLabels:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field labels", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Labels); err != nil {
					return fmt.Errorf("unmarshal field labels: %w", err)
				}
			}
		case alertevent.FieldAnnotations:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field annotations", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Annotations); err != nil {
					return fmt.Errorf("unmarshal field annotations: %w", err)
				}
			}
		case alertevent.FieldRawPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field raw_payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RawPayload); err != nil {
					return fmt.Errorf("unmarshal field raw_payload: %w", err)
				}
			}
		case alertevent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case alertevent.FieldStartsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field starts_at", values[i])
			} else if value.Valid {
				_m.StartsAt = value.Time
			}
		case alertevent.FieldEndsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ends_at", values[i])
			} else if value.Valid {
				_m.EndsAt = new(time.Time)
				*_m.EndsAt = value.Time
			}
		case alertevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AlertEvent.
// This includes values selected through modifiers, order, etc.
func (_m *AlertEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroups queries the "groups" edge of the AlertEvent entity.
func (_m *AlertEvent) QueryGroups() *AlertGroupQuery {
	return NewAlertEventClient(_m.config).QueryGroups(_m)
}

// Update returns a builder for updating this AlertEvent.
// Note that you need to call AlertEvent.Unwrap() before calling this method if this AlertEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AlertEvent) Update() *AlertEventUpdateOne {
	return NewAlertEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AlertEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AlertEvent) Unwrap() *AlertEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AlertEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AlertEvent) String() string {
	var builder strings.Builder
	builder.WriteString("AlertEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("alert_source_profile_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AlertSourceProfileID))
	builder.WriteString(", ")
	builder.WriteString("source_fingerprint=")
	builder.WriteString(_m.SourceFingerprint)
	builder.WriteString(", ")
	builder.WriteString("canonical_fingerprint=")
	builder.WriteString(_m.CanonicalFingerprint)
	builder.WriteString(", ")
	builder.WriteString("labels=")
	builder.WriteString(fmt.Sprintf("%v", _m.Labels))
	builder.WriteString(", ")
	builder.WriteString("annotations=")
	builder.WriteString(fmt.Sprintf("%v", _m.Annotations))
	builder.WriteString(", ")
	builder.WriteString("raw_payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.RawPayload))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("starts_at=")
	builder.WriteString(_m.StartsAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.EndsAt; v != nil {
		builder.WriteString("ends_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AlertEvents is a parsable slice of AlertEvent.
type AlertEvents []*AlertEvent
