// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/openclarion/openclarion/internal/persistence/ent/chatsession"
	"github.com/openclarion/openclarion/internal/persistence/ent/chatturn"
	"github.com/openclarion/openclarion/internal/persistence/ent/predicate"
)

// ChatTurnQuery is the builder for querying ChatTurn entities.
type ChatTurnQuery struct {
	config
	ctx         *QueryContext
	order       []chatturn.OrderOption
	inters      []Interceptor
	predicates  []predicate.ChatTurn
	withSession *ChatSessionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChatTurnQuery builder.
func (_q *ChatTurnQuery) Where(ps ...predicate.ChatTurn) *ChatTurnQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ChatTurnQuery) Limit(limit int) *ChatTurnQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ChatTurnQuery) Offset(offset int) *ChatTurnQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ChatTurnQuery) Unique(unique bool) *ChatTurnQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ChatTurnQuery) Order(o ...chatturn.OrderOption) *ChatTurnQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySession chains the current query on the "session" edge.
func (_q *ChatTurnQuery) QuerySession() *ChatSessionQuery {
	query := (&ChatSessionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(chatturn.Table, chatturn.FieldID, selector),
			sqlgraph.To(chatsession.Table, chatsession.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, chatturn.SessionTable, chatturn.SessionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ChatTurn entity from the query.
// Returns a *NotFoundError when no ChatTurn was found.
func (_q *ChatTurnQuery) First(ctx context.Context) (*ChatTurn, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{chatturn.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ChatTurnQuery) FirstX(ctx context.Context) *ChatTurn {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ChatTurn ID from the query.
// Returns a *NotFoundError when no ChatTurn ID was found.
func (_q *ChatTurnQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{chatturn.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ChatTurnQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ChatTurn entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ChatTurn entity is found.
// Returns a *NotFoundError when no ChatTurn entities are found.
func (_q *ChatTurnQuery) Only(ctx context.Context) (*ChatTurn, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{chatturn.Label}
	default:
		return nil, &NotSingularError{chatturn.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ChatTurnQuery) OnlyX(ctx context.Context) *ChatTurn {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ChatTurn ID in the query.
// Returns a *NotSingularError when more than one ChatTurn ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ChatTurnQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{chatturn.Label}
	default:
		err = &NotSingularError{chatturn.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ChatTurnQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ChatTurns.
func (_q *ChatTurnQuery) All(ctx context.Context) ([]*ChatTurn, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ChatTurn, *ChatTurnQuery]()
	return withInterceptors[[]*ChatTurn](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ChatTurnQuery) AllX(ctx context.Context) []*ChatTurn {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ChatTurn IDs.
func (_q *ChatTurnQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(chatturn.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ChatTurnQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ChatTurnQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ChatTurnQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ChatTurnQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ChatTurnQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ChatTurnQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChatTurnQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ChatTurnQuery) Clone() *ChatTurnQuery {
	if _q == nil {
		return nil
	}
	return &ChatTurnQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]chatturn.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.ChatTurn{}, _q.predicates...),
		withSession: _q.withSession.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithSession tells the query-builder to eager-load the nodes that are connected to
// the "session" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChatTurnQuery) WithSession(opts ...func(*ChatSessionQuery)) *ChatTurnQuery {
	query := (&ChatSessionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSession = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ChatSessionID int `json:"chat_session_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ChatTurn.Query().
//		GroupBy(chatturn.FieldChatSessionID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ChatTurnQuery) GroupBy(field string, fields ...string) *ChatTurnGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChatTurnGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = chatturn.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ChatSessionID int `json:"chat_session_id,omitempty"`
//	}
//
//	client.ChatTurn.Query().
//		Select(chatturn.FieldChatSessionID).
//		Scan(ctx, &v)
func (_q *ChatTurnQuery) Select(fields ...string) *ChatTurnSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ChatTurnSelect{ChatTurnQuery: _q}
	sbuild.label = chatturn.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChatTurnSelect configured with the given aggregations.
func (_q *ChatTurnQuery) Aggregate(fns ...AggregateFunc) *ChatTurnSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ChatTurnQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !chatturn.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ChatTurnQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ChatTurn, error) {
	var (
		nodes       = []*ChatTurn{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withSession != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ChatTurn).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ChatTurn{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSession; query != nil {
		if err := _q.loadSession(ctx, query, nodes, nil,
			func(n *ChatTurn, e *ChatSession) { n.Edges.Session = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ChatTurnQuery) loadSession(ctx context.Context, query *ChatSessionQuery, nodes []*ChatTurn, init func(*ChatTurn), assign func(*ChatTurn, *ChatSession)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ChatTurn)
	for i := range nodes {
		fk := nodes[i].ChatSessionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(chatsession.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "chat_session_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ChatTurnQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ChatTurnQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(chatturn.Table, chatturn.Columns, sqlgraph.NewFieldSpec(chatturn.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatturn.FieldID)
		for i := range fields {
			if fields[i] != chatturn.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withSession != nil {
			_spec.Node.AddColumnOnce(chatturn.FieldChatSessionID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ChatTurnQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(chatturn.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = chatturn.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ChatTurnGroupBy is the group-by builder for ChatTurn entities.
type ChatTurnGroupBy struct {
	selector
	build *ChatTurnQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ChatTurnGroupBy) Aggregate(fns ...AggregateFunc) *ChatTurnGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ChatTurnGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChatTurnQuery, *ChatTurnGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ChatTurnGroupBy) sqlScan(ctx context.Context, root *ChatTurnQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChatTurnSelect is the builder for selecting fields of ChatTurn entities.
type ChatTurnSelect struct {
	*ChatTurnQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ChatTurnSelect) Aggregate(fns ...AggregateFunc) *ChatTurnSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ChatTurnSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChatTurnQuery, *ChatTurnSelect](ctx, _s.ChatTurnQuery, _s, _s.inters, v)
}

func (_s *ChatTurnSelect) sqlScan(ctx context.Context, root *ChatTurnQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
