// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/openclarion/openclarion/internal/persistence/ent/chatsession"
	"github.com/openclarion/openclarion/internal/persistence/ent/chatturn"
)

// ChatTurnCreate is the builder for creating a ChatTurn entity.
type ChatTurnCreate struct {
	config
	mutation *ChatTurnMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetChatSessionID sets the "chat_session_id" field.
func (_c *ChatTurnCreate) SetChatSessionID(v int) *ChatTurnCreate {
	_c.mutation.SetChatSessionID(v)
	return _c
}

// SetMessageID sets the "message_id" field.
func (_c *ChatTurnCreate) SetMessageID(v string) *ChatTurnCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetSequence sets the "sequence" field.
func (_c *ChatTurnCreate) SetSequence(v int) *ChatTurnCreate {
	_c.mutation.SetSequence(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *ChatTurnCreate) SetRole(v string) *ChatTurnCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetActorSubject sets the "actor_subject" field.
func (_c *ChatTurnCreate) SetActorSubject(v string) *ChatTurnCreate {
	_c.mutation.SetActorSubject(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *ChatTurnCreate) SetContent(v string) *ChatTurnCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *ChatTurnCreate) SetMetadata(v json.RawMessage) *ChatTurnCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetOccurredAt sets the "occurred_at" field.
func (_c *ChatTurnCreate) SetOccurredAt(v time.Time) *ChatTurnCreate {
	_c.mutation.SetOccurredAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChatTurnCreate) SetCreatedAt(v time.Time) *ChatTurnCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChatTurnCreate) SetNillableCreatedAt(v *time.Time) *ChatTurnCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetSessionID sets the "session" edge to the ChatSession entity by ID.
func (_c *ChatTurnCreate) SetSessionID(id int) *ChatTurnCreate {
	_c.mutation.SetSessionID(id)
	return _c
}

// SetSession sets the "session" edge to the ChatSession entity.
func (_c *ChatTurnCreate) SetSession(v *ChatSession) *ChatTurnCreate {
	return _c.SetSessionID(v.ID)
}

// Mutation returns the ChatTurnMutation object of the builder.
func (_c *ChatTurnCreate) Mutation() *ChatTurnMutation {
	return _c.mutation
}

// Save creates the ChatTurn in the database.
func (_c *ChatTurnCreate) Save(ctx context.Context) (*ChatTurn, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChatTurnCreate) SaveX(ctx context.Context) *ChatTurn {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatTurnCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatTurnCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChatTurnCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chatturn.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChatTurnCreate) check() error {
	if _, ok := _c.mutation.ChatSessionID(); !ok {
		return &ValidationError{Name: "chat_session_id", err: errors.New(`ent: missing required field "ChatTurn.chat_session_id"`)}
	}
	if _, ok := _c.mutation.MessageID(); !ok {
		return &ValidationError{Name: "message_id", err: errors.New(`ent: missing required field "ChatTurn.message_id"`)}
	}
	if v, ok := _c.mutation.MessageID(); ok {
		if err := chatturn.MessageIDValidator(v); err != nil {
			return &ValidationError{Name: "message_id", err: fmt.Errorf(`ent: validator failed for field "ChatTurn.message_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Sequence(); !ok {
		return &ValidationError{Name: "sequence", err: errors.New(`ent: missing required field "ChatTurn.sequence"`)}
	}
	if v, ok := _c.mutation.Sequence(); ok {
		if err := chatturn.SequenceValidator(v); err != nil {
			return &ValidationError{Name: "sequence", err: fmt.Errorf(`ent: validator failed for field "ChatTurn.sequence": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "ChatTurn.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := chatturn.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "ChatTurn.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActorSubject(); !ok {
		return &ValidationError{Name: "actor_subject", err: errors.New(`ent: missing required field "ChatTurn.actor_subject"`)}
	}
	if v, ok := _c.mutation.ActorSubject(); ok {
		if err := chatturn.ActorSubjectValidator(v); err != nil {
			return &ValidationError{Name: "actor_subject", err: fmt.Errorf(`ent: validator failed for field "ChatTurn.actor_subject": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "ChatTurn.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := chatturn.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "ChatTurn.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OccurredAt(); !ok {
		return &ValidationError{Name: "occurred_at", err: errors.New(`ent: missing required field "ChatTurn.occurred_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChatTurn.created_at"`)}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "ChatTurn.session"`)}
	}
	return nil
}

func (_c *ChatTurnCreate) sqlSave(ctx context.Context) (*ChatTurn, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChatTurnCreate) createSpec() (*ChatTurn, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatTurn{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chatturn.Table, sqlgraph.NewFieldSpec(chatturn.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.MessageID(); ok {
		_spec.SetField(chatturn.FieldMessageID, field.TypeString, value)
		_node.MessageID = value
	}
	if value, ok := _c.mutation.Sequence(); ok {
		_spec.SetField(chatturn.FieldSequence, field.TypeInt, value)
		_node.Sequence = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(chatturn.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.ActorSubject(); ok {
		_spec.SetField(chatturn.FieldActorSubject, field.TypeString, value)
		_node.ActorSubject = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(chatturn.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(chatturn.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.OccurredAt(); ok {
		_spec.SetField(chatturn.FieldOccurredAt, field.TypeTime, value)
		_node.OccurredAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chatturn.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatturn.SessionTable,
			Columns: []string{chatturn.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatsession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChatSessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChatTurn.Create().
//		SetChatSessionID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChatTurnUpsert) {
//			SetChatSessionID(v+v).
//		}).
//		Exec(ctx)
func (_c *ChatTurnCreate) OnConflict(opts ...sql.ConflictOption) *ChatTurnUpsertOne {
	_c.conflict = opts
	return &ChatTurnUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChatTurn.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChatTurnCreate) OnConflictColumns(columns ...string) *ChatTurnUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChatTurnUpsertOne{
		create: _c,
	}
}

type (
	// ChatTurnUpsertOne is the builder for "upsert"-ing
	//  one ChatTurn node.
	ChatTurnUpsertOne struct {
		create *ChatTurnCreate
	}

	// ChatTurnUpsert is the "OnConflict" setter.
	ChatTurnUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ChatTurn.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChatTurnUpsertOne) UpdateNewValues() *ChatTurnUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ChatSessionID(); exists {
			s.SetIgnore(chatturn.FieldChatSessionID)
		}
		if _, exists := u.create.mutation.MessageID(); exists {
			s.SetIgnore(chatturn.FieldMessageID)
		}
		if _, exists := u.create.mutation.Sequence(); exists {
			s.SetIgnore(chatturn.FieldSequence)
		}
		if _, exists := u.create.mutation.Role(); exists {
			s.SetIgnore(chatturn.FieldRole)
		}
		if _, exists := u.create.mutation.ActorSubject(); exists {
			s.SetIgnore(chatturn.FieldActorSubject)
		}
		if _, exists := u.create.mutation.Content(); exists {
			s.SetIgnore(chatturn.FieldContent)
		}
		if _, exists := u.create.mutation.Metadata(); exists {
			s.SetIgnore(chatturn.FieldMetadata)
		}
		if _, exists := u.create.mutation.OccurredAt(); exists {
			s.SetIgnore(chatturn.FieldOccurredAt)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(chatturn.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChatTurn.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChatTurnUpsertOne) Ignore() *ChatTurnUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChatTurnUpsertOne) DoNothing() *ChatTurnUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChatTurnCreate.OnConflict
// documentation for more info.
func (u *ChatTurnUpsertOne) Update(set func(*ChatTurnUpsert)) *ChatTurnUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChatTurnUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *ChatTurnUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChatTurnCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChatTurnUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChatTurnUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChatTurnUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChatTurnCreateBulk is the builder for creating many ChatTurn entities in bulk.
type ChatTurnCreateBulk struct {
	config
	err      error
	builders []*ChatTurnCreate
	conflict []sql.ConflictOption
}

// Save creates the ChatTurn entities in the database.
func (_c *ChatTurnCreateBulk) Save(ctx context.Context) ([]*ChatTurn, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChatTurn, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatTurnMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChatTurnCreateBulk) SaveX(ctx context.Context) []*ChatTurn {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatTurnCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatTurnCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChatTurn.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChatTurnUpsert) {
//			SetChatSessionID(v+v).
//		}).
//		Exec(ctx)
func (_c *ChatTurnCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChatTurnUpsertBulk {
	_c.conflict = opts
	return &ChatTurnUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChatTurn.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChatTurnCreateBulk) OnConflictColumns(columns ...string) *ChatTurnUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChatTurnUpsertBulk{
		create: _c,
	}
}

// ChatTurnUpsertBulk is the builder for "upsert"-ing
// a bulk of ChatTurn nodes.
type ChatTurnUpsertBulk struct {
	create *ChatTurnCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChatTurn.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChatTurnUpsertBulk) UpdateNewValues() *ChatTurnUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ChatSessionID(); exists {
				s.SetIgnore(chatturn.FieldChatSessionID)
			}
			if _, exists := b.mutation.MessageID(); exists {
				s.SetIgnore(chatturn.FieldMessageID)
			}
			if _, exists := b.mutation.Sequence(); exists {
				s.SetIgnore(chatturn.FieldSequence)
			}
			if _, exists := b.mutation.Role(); exists {
				s.SetIgnore(chatturn.FieldRole)
			}
			if _, exists := b.mutation.ActorSubject(); exists {
				s.SetIgnore(chatturn.FieldActorSubject)
			}
			if _, exists := b.mutation.Content(); exists {
				s.SetIgnore(chatturn.FieldContent)
			}
			if _, exists := b.mutation.Metadata(); exists {
				s.SetIgnore(chatturn.FieldMetadata)
			}
			if _, exists := b.mutation.OccurredAt(); exists {
				s.SetIgnore(chatturn.FieldOccurredAt)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(chatturn.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChatTurn.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChatTurnUpsertBulk) Ignore() *ChatTurnUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChatTurnUpsertBulk) DoNothing() *ChatTurnUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChatTurnCreateBulk.OnConflict
// documentation for more info.
func (u *ChatTurnUpsertBulk) Update(set func(*ChatTurnUpsert)) *ChatTurnUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChatTurnUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *ChatTurnUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChatTurnCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChatTurnCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChatTurnUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
