// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/openclarion/openclarion/internal/persistence/ent/diagnosistaskevent"
	"github.com/openclarion/openclarion/internal/persistence/ent/predicate"
)

// DiagnosisTaskEventDelete is the builder for deleting a DiagnosisTaskEvent entity.
type DiagnosisTaskEventDelete struct {
	config
	hooks    []Hook
	mutation *DiagnosisTaskEventMutation
}

// Where appends a list predicates to the DiagnosisTaskEventDelete builder.
func (_d *DiagnosisTaskEventDelete) Where(ps ...predicate.DiagnosisTaskEvent) *DiagnosisTaskEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DiagnosisTaskEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DiagnosisTaskEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DiagnosisTaskEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(diagnosistaskevent.Table, sqlgraph.NewFieldSpec(diagnosistaskevent.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DiagnosisTaskEventDeleteOne is the builder for deleting a single DiagnosisTaskEvent entity.
type DiagnosisTaskEventDeleteOne struct {
	_d *DiagnosisTaskEventDelete
}

// Where appends a list predicates to the DiagnosisTaskEventDelete builder.
func (_d *DiagnosisTaskEventDeleteOne) Where(ps ...predicate.DiagnosisTaskEvent) *DiagnosisTaskEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DiagnosisTaskEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{diagnosistaskevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DiagnosisTaskEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
