// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/openclarion/openclarion/internal/persistence/ent/diagnosistask"
	"github.com/openclarion/openclarion/internal/persistence/ent/diagnosistaskevent"
	"github.com/openclarion/openclarion/internal/persistence/ent/predicate"
)

// DiagnosisTaskUpdate is the builder for updating DiagnosisTask entities.
type DiagnosisTaskUpdate struct {
	config
	hooks    []Hook
	mutation *DiagnosisTaskMutation
}

// Where appends a list predicates to the DiagnosisTaskUpdate builder.
func (_u *DiagnosisTaskUpdate) Where(ps ...predicate.DiagnosisTask) *DiagnosisTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *DiagnosisTaskUpdate) SetStatus(v string) *DiagnosisTaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DiagnosisTaskUpdate) SetNillableStatus(v *string) *DiagnosisTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *DiagnosisTaskUpdate) SetFailureReason(v string) *DiagnosisTaskUpdate {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *DiagnosisTaskUpdate) SetNillableFailureReason(v *string) *DiagnosisTaskUpdate {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *DiagnosisTaskUpdate) ClearFailureReason() *DiagnosisTaskUpdate {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *DiagnosisTaskUpdate) SetStartedAt(v time.Time) *DiagnosisTaskUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *DiagnosisTaskUpdate) SetNillableStartedAt(v *time.Time) *DiagnosisTaskUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *DiagnosisTaskUpdate) ClearStartedAt() *DiagnosisTaskUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *DiagnosisTaskUpdate) SetFinishedAt(v time.Time) *DiagnosisTaskUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *DiagnosisTaskUpdate) SetNillableFinishedAt(v *time.Time) *DiagnosisTaskUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *DiagnosisTaskUpdate) ClearFinishedAt() *DiagnosisTaskUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DiagnosisTaskUpdate) SetUpdatedAt(v time.Time) *DiagnosisTaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddEventIDs adds the "events" edge to the DiagnosisTaskEvent entity by IDs.
func (_u *DiagnosisTaskUpdate) AddEventIDs(ids ...int) *DiagnosisTaskUpdate {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the DiagnosisTaskEvent entity.
func (_u *DiagnosisTaskUpdate) AddEvents(v ...*DiagnosisTaskEvent) *DiagnosisTaskUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the DiagnosisTaskMutation object of the builder.
func (_u *DiagnosisTaskUpdate) Mutation() *DiagnosisTaskMutation {
	return _u.mutation
}

// ClearEvents clears all "events" edges to the DiagnosisTaskEvent entity.
func (_u *DiagnosisTaskUpdate) ClearEvents() *DiagnosisTaskUpdate {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to DiagnosisTaskEvent entities by IDs.
func (_u *DiagnosisTaskUpdate) RemoveEventIDs(ids ...int) *DiagnosisTaskUpdate {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to DiagnosisTaskEvent entities.
func (_u *DiagnosisTaskUpdate) RemoveEvents(v ...*DiagnosisTaskEvent) *DiagnosisTaskUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DiagnosisTaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiagnosisTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DiagnosisTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiagnosisTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DiagnosisTaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := diagnosistask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DiagnosisTaskUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := diagnosistask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DiagnosisTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FailureReason(); ok {
		if err := diagnosistask.FailureReasonValidator(v); err != nil {
			return &ValidationError{Name: "failure_reason", err: fmt.Errorf(`ent: validator failed for field "DiagnosisTask.failure_reason": %w`, err)}
		}
	}
	if _u.mutation.SnapshotCleared() && len(_u.mutation.SnapshotIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DiagnosisTask.snapshot"`)
	}
	return nil
}

func (_u *DiagnosisTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(diagnosistask.Table, diagnosistask.Columns, sqlgraph.NewFieldSpec(diagnosistask.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(diagnosistask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(diagnosistask.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(diagnosistask.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(diagnosistask.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(diagnosistask.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(diagnosistask.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(diagnosistask.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(diagnosistask.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   diagnosistask.EventsTable,
			Columns: []string{diagnosistask.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagnosistaskevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   diagnosistask.EventsTable,
			Columns: []string{diagnosistask.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagnosistaskevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   diagnosistask.EventsTable,
			Columns: []string{diagnosistask.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagnosistaskevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{diagnosistask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DiagnosisTaskUpdateOne is the builder for updating a single DiagnosisTask entity.
type DiagnosisTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DiagnosisTaskMutation
}

// SetStatus sets the "status" field.
func (_u *DiagnosisTaskUpdateOne) SetStatus(v string) *DiagnosisTaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DiagnosisTaskUpdateOne) SetNillableStatus(v *string) *DiagnosisTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *DiagnosisTaskUpdateOne) SetFailureReason(v string) *DiagnosisTaskUpdateOne {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *DiagnosisTaskUpdateOne) SetNillableFailureReason(v *string) *DiagnosisTaskUpdateOne {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *DiagnosisTaskUpdateOne) ClearFailureReason() *DiagnosisTaskUpdateOne {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *DiagnosisTaskUpdateOne) SetStartedAt(v time.Time) *DiagnosisTaskUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *DiagnosisTaskUpdateOne) SetNillableStartedAt(v *time.Time) *DiagnosisTaskUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *DiagnosisTaskUpdateOne) ClearStartedAt() *DiagnosisTaskUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *DiagnosisTaskUpdateOne) SetFinishedAt(v time.Time) *DiagnosisTaskUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *DiagnosisTaskUpdateOne) SetNillableFinishedAt(v *time.Time) *DiagnosisTaskUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *DiagnosisTaskUpdateOne) ClearFinishedAt() *DiagnosisTaskUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DiagnosisTaskUpdateOne) SetUpdatedAt(v time.Time) *DiagnosisTaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddEventIDs adds the "events" edge to the DiagnosisTaskEvent entity by IDs.
func (_u *DiagnosisTaskUpdateOne) AddEventIDs(ids ...int) *DiagnosisTaskUpdateOne {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the DiagnosisTaskEvent entity.
func (_u *DiagnosisTaskUpdateOne) AddEvents(v ...*DiagnosisTaskEvent) *DiagnosisTaskUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the DiagnosisTaskMutation object of the builder.
func (_u *DiagnosisTaskUpdateOne) Mutation() *DiagnosisTaskMutation {
	return _u.mutation
}

// ClearEvents clears all "events" edges to the DiagnosisTaskEvent entity.
func (_u *DiagnosisTaskUpdateOne) ClearEvents() *DiagnosisTaskUpdateOne {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to DiagnosisTaskEvent entities by IDs.
func (_u *DiagnosisTaskUpdateOne) RemoveEventIDs(ids ...int) *DiagnosisTaskUpdateOne {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to DiagnosisTaskEvent entities.
func (_u *DiagnosisTaskUpdateOne) RemoveEvents(v ...*DiagnosisTaskEvent) *DiagnosisTaskUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Where appends a list predicates to the DiagnosisTaskUpdate builder.
func (_u *DiagnosisTaskUpdateOne) Where(ps ...predicate.DiagnosisTask) *DiagnosisTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DiagnosisTaskUpdateOne) Select(field string, fields ...string) *DiagnosisTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DiagnosisTask entity.
func (_u *DiagnosisTaskUpdateOne) Save(ctx context.Context) (*DiagnosisTask, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiagnosisTaskUpdateOne) SaveX(ctx context.Context) *DiagnosisTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DiagnosisTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiagnosisTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DiagnosisTaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := diagnosistask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DiagnosisTaskUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := diagnosistask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DiagnosisTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FailureReason(); ok {
		if err := diagnosistask.FailureReasonValidator(v); err != nil {
			return &ValidationError{Name: "failure_reason", err: fmt.Errorf(`ent: validator failed for field "DiagnosisTask.failure_reason": %w`, err)}
		}
	}
	if _u.mutation.SnapshotCleared() && len(_u.mutation.SnapshotIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DiagnosisTask.snapshot"`)
	}
	return nil
}

func (_u *DiagnosisTaskUpdateOne) sqlSave(ctx context.Context) (_node *DiagnosisTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(diagnosistask.Table, diagnosistask.Columns, sqlgraph.NewFieldSpec(diagnosistask.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DiagnosisTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, diagnosistask.FieldID)
		for _, f := range fields {
			if !diagnosistask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != diagnosistask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(diagnosistask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(diagnosistask.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(diagnosistask.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(diagnosistask.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(diagnosistask.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(diagnosistask.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(diagnosistask.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(diagnosistask.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   diagnosistask.EventsTable,
			Columns: []string{diagnosistask.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagnosistaskevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   diagnosistask.EventsTable,
			Columns: []string{diagnosistask.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagnosistaskevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   diagnosistask.EventsTable,
			Columns: []string{diagnosistask.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diagnosistaskevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DiagnosisTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{diagnosistask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
