// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/openclarion/openclarion/internal/persistence/ent/alertgroup"
	"github.com/openclarion/openclarion/internal/persistence/ent/diagnosistask"
	"github.com/openclarion/openclarion/internal/persistence/ent/evidencesnapshot"
	"github.com/openclarion/openclarion/internal/persistence/ent/predicate"
)

// EvidenceSnapshotQuery is the builder for querying EvidenceSnapshot entities.
type EvidenceSnapshotQuery struct {
	config
	ctx        *QueryContext
	order      []evidencesnapshot.OrderOption
	inters     []Interceptor
	predicates []predicate.EvidenceSnapshot
	withGroup  *AlertGroupQuery
	withTasks  *DiagnosisTaskQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EvidenceSnapshotQuery builder.
func (_q *EvidenceSnapshotQuery) Where(ps ...predicate.EvidenceSnapshot) *EvidenceSnapshotQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *EvidenceSnapshotQuery) Limit(limit int) *EvidenceSnapshotQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *EvidenceSnapshotQuery) Offset(offset int) *EvidenceSnapshotQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *EvidenceSnapshotQuery) Unique(unique bool) *EvidenceSnapshotQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *EvidenceSnapshotQuery) Order(o ...evidencesnapshot.OrderOption) *EvidenceSnapshotQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryGroup chains the current query on the "group" edge.
func (_q *EvidenceSnapshotQuery) QueryGroup() *AlertGroupQuery {
	query := (&AlertGroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(evidencesnapshot.Table, evidencesnapshot.FieldID, selector),
			sqlgraph.To(alertgroup.Table, alertgroup.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, evidencesnapshot.GroupTable, evidencesnapshot.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTasks chains the current query on the "tasks" edge.
func (_q *EvidenceSnapshotQuery) QueryTasks() *DiagnosisTaskQuery {
	query := (&DiagnosisTaskClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(evidencesnapshot.Table, evidencesnapshot.FieldID, selector),
			sqlgraph.To(diagnosistask.Table, diagnosistask.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, evidencesnapshot.TasksTable, evidencesnapshot.TasksColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EvidenceSnapshot entity from the query.
// Returns a *NotFoundError when no EvidenceSnapshot was found.
func (_q *EvidenceSnapshotQuery) First(ctx context.Context) (*EvidenceSnapshot, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{evidencesnapshot.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *EvidenceSnapshotQuery) FirstX(ctx context.Context) *EvidenceSnapshot {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EvidenceSnapshot ID from the query.
// Returns a *NotFoundError when no EvidenceSnapshot ID was found.
func (_q *EvidenceSnapshotQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{evidencesnapshot.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *EvidenceSnapshotQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EvidenceSnapshot entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EvidenceSnapshot entity is found.
// Returns a *NotFoundError when no EvidenceSnapshot entities are found.
func (_q *EvidenceSnapshotQuery) Only(ctx context.Context) (*EvidenceSnapshot, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{evidencesnapshot.Label}
	default:
		return nil, &NotSingularError{evidencesnapshot.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *EvidenceSnapshotQuery) OnlyX(ctx context.Context) *EvidenceSnapshot {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EvidenceSnapshot ID in the query.
// Returns a *NotSingularError when more than one EvidenceSnapshot ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *EvidenceSnapshotQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{evidencesnapshot.Label}
	default:
		err = &NotSingularError{evidencesnapshot.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *EvidenceSnapshotQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EvidenceSnapshots.
func (_q *EvidenceSnapshotQuery) All(ctx context.Context) ([]*EvidenceSnapshot, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EvidenceSnapshot, *EvidenceSnapshotQuery]()
	return withInterceptors[[]*EvidenceSnapshot](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *EvidenceSnapshotQuery) AllX(ctx context.Context) []*EvidenceSnapshot {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EvidenceSnapshot IDs.
func (_q *EvidenceSnapshotQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(evidencesnapshot.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *EvidenceSnapshotQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *EvidenceSnapshotQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*EvidenceSnapshotQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *EvidenceSnapshotQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *EvidenceSnapshotQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *EvidenceSnapshotQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EvidenceSnapshotQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *EvidenceSnapshotQuery) Clone() *EvidenceSnapshotQuery {
	if _q == nil {
		return nil
	}
	return &EvidenceSnapshotQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]evidencesnapshot.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.EvidenceSnapshot{}, _q.predicates...),
		withGroup:  _q.withGroup.Clone(),
		withTasks:  _q.withTasks.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EvidenceSnapshotQuery) WithGroup(opts ...func(*AlertGroupQuery)) *EvidenceSnapshotQuery {
	query := (&AlertGroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroup = query
	return _q
}

// WithTasks tells the query-builder to eager-load the nodes that are connected to
// the "tasks" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EvidenceSnapshotQuery) WithTasks(opts ...func(*DiagnosisTaskQuery)) *EvidenceSnapshotQuery {
	query := (&DiagnosisTaskClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTasks = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AlertGroupID int `json:"alert_group_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EvidenceSnapshot.Query().
//		GroupBy(evidencesnapshot.FieldAlertGroupID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *EvidenceSnapshotQuery) GroupBy(field string, fields ...string) *EvidenceSnapshotGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EvidenceSnapshotGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = evidencesnapshot.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AlertGroupID int `json:"alert_group_id,omitempty"`
//	}
//
//	client.EvidenceSnapshot.Query().
//		Select(evidencesnapshot.FieldAlertGroupID).
//		Scan(ctx, &v)
func (_q *EvidenceSnapshotQuery) Select(fields ...string) *EvidenceSnapshotSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &EvidenceSnapshotSelect{EvidenceSnapshotQuery: _q}
	sbuild.label = evidencesnapshot.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EvidenceSnapshotSelect configured with the given aggregations.
func (_q *EvidenceSnapshotQuery) Aggregate(fns ...AggregateFunc) *EvidenceSnapshotSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *EvidenceSnapshotQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !evidencesnapshot.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *EvidenceSnapshotQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EvidenceSnapshot, error) {
	var (
		nodes       = []*EvidenceSnapshot{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withGroup != nil,
			_q.withTasks != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EvidenceSnapshot).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EvidenceSnapshot{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withGroup; query != nil {
		if err := _q.loadGroup(ctx, query, nodes, nil,
			func(n *EvidenceSnapshot, e *AlertGroup) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTasks; query != nil {
		if err := _q.loadTasks(ctx, query, nodes,
			func(n *EvidenceSnapshot) { n.Edges.Tasks = []*DiagnosisTask{} },
			func(n *EvidenceSnapshot, e *DiagnosisTask) { n.Edges.Tasks = append(n.Edges.Tasks, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *EvidenceSnapshotQuery) loadGroup(ctx context.Context, query *AlertGroupQuery, nodes []*EvidenceSnapshot, init func(*EvidenceSnapshot), assign func(*EvidenceSnapshot, *AlertGroup)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*EvidenceSnapshot)
	for i := range nodes {
		fk := nodes[i].AlertGroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(alertgroup.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "alert_group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *EvidenceSnapshotQuery) loadTasks(ctx context.Context, query *DiagnosisTaskQuery, nodes []*EvidenceSnapshot, init func(*EvidenceSnapshot), assign func(*EvidenceSnapshot, *DiagnosisTask)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*EvidenceSnapshot)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(diagnosistask.FieldEvidenceSnapshotID)
	}
	query.Where(predicate.DiagnosisTask(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(evidencesnapshot.TasksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.EvidenceSnapshotID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "evidence_snapshot_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *EvidenceSnapshotQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *EvidenceSnapshotQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(evidencesnapshot.Table, evidencesnapshot.Columns, sqlgraph.NewFieldSpec(evidencesnapshot.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, evidencesnapshot.FieldID)
		for i := range fields {
			if fields[i] != evidencesnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withGroup != nil {
			_spec.Node.AddColumnOnce(evidencesnapshot.FieldAlertGroupID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *EvidenceSnapshotQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(evidencesnapshot.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = evidencesnapshot.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EvidenceSnapshotGroupBy is the group-by builder for EvidenceSnapshot entities.
type EvidenceSnapshotGroupBy struct {
	selector
	build *EvidenceSnapshotQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *EvidenceSnapshotGroupBy) Aggregate(fns ...AggregateFunc) *EvidenceSnapshotGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *EvidenceSnapshotGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EvidenceSnapshotQuery, *EvidenceSnapshotGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *EvidenceSnapshotGroupBy) sqlScan(ctx context.Context, root *EvidenceSnapshotQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EvidenceSnapshotSelect is the builder for selecting fields of EvidenceSnapshot entities.
type EvidenceSnapshotSelect struct {
	*EvidenceSnapshotQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *EvidenceSnapshotSelect) Aggregate(fns ...AggregateFunc) *EvidenceSnapshotSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *EvidenceSnapshotSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EvidenceSnapshotQuery, *EvidenceSnapshotSelect](ctx, _s.EvidenceSnapshotQuery, _s, _s.inters, v)
}

func (_s *EvidenceSnapshotSelect) sqlScan(ctx context.Context, root *EvidenceSnapshotQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
