// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/openclarion/openclarion/internal/persistence/ent/finalreport"
	"github.com/openclarion/openclarion/internal/persistence/ent/predicate"
	"github.com/openclarion/openclarion/internal/persistence/ent/reportnotificationdelivery"
	"github.com/openclarion/openclarion/internal/persistence/ent/subreport"
)

// FinalReportUpdate is the builder for updating FinalReport entities.
type FinalReportUpdate struct {
	config
	hooks    []Hook
	mutation *FinalReportMutation
}

// Where appends a list predicates to the FinalReportUpdate builder.
func (_u *FinalReportUpdate) Where(ps ...predicate.FinalReport) *FinalReportUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// AddSubReportIDs adds the "sub_reports" edge to the SubReport entity by IDs.
func (_u *FinalReportUpdate) AddSubReportIDs(ids ...int) *FinalReportUpdate {
	_u.mutation.AddSubReportIDs(ids...)
	return _u
}

// AddSubReports adds the "sub_reports" edges to the SubReport entity.
func (_u *FinalReportUpdate) AddSubReports(v ...*SubReport) *FinalReportUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubReportIDs(ids...)
}

// AddNotificationDeliveryIDs adds the "notification_deliveries" edge to the ReportNotificationDelivery entity by IDs.
func (_u *FinalReportUpdate) AddNotificationDeliveryIDs(ids ...int) *FinalReportUpdate {
	_u.mutation.AddNotificationDeliveryIDs(ids...)
	return _u
}

// AddNotificationDeliveries adds the "notification_deliveries" edges to the ReportNotificationDelivery entity.
func (_u *FinalReportUpdate) AddNotificationDeliveries(v ...*ReportNotificationDelivery) *FinalReportUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNotificationDeliveryIDs(ids...)
}

// Mutation returns the FinalReportMutation object of the builder.
func (_u *FinalReportUpdate) Mutation() *FinalReportMutation {
	return _u.mutation
}

// ClearSubReports clears all "sub_reports" edges to the SubReport entity.
func (_u *FinalReportUpdate) ClearSubReports() *FinalReportUpdate {
	_u.mutation.ClearSubReports()
	return _u
}

// RemoveSubReportIDs removes the "sub_reports" edge to SubReport entities by IDs.
func (_u *FinalReportUpdate) RemoveSubReportIDs(ids ...int) *FinalReportUpdate {
	_u.mutation.RemoveSubReportIDs(ids...)
	return _u
}

// RemoveSubReports removes "sub_reports" edges to SubReport entities.
func (_u *FinalReportUpdate) RemoveSubReports(v ...*SubReport) *FinalReportUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubReportIDs(ids...)
}

// ClearNotificationDeliveries clears all "notification_deliveries" edges to the ReportNotificationDelivery entity.
func (_u *FinalReportUpdate) ClearNotificationDeliveries() *FinalReportUpdate {
	_u.mutation.ClearNotificationDeliveries()
	return _u
}

// RemoveNotificationDeliveryIDs removes the "notification_deliveries" edge to ReportNotificationDelivery entities by IDs.
func (_u *FinalReportUpdate) RemoveNotificationDeliveryIDs(ids ...int) *FinalReportUpdate {
	_u.mutation.RemoveNotificationDeliveryIDs(ids...)
	return _u
}

// RemoveNotificationDeliveries removes "notification_deliveries" edges to ReportNotificationDelivery entities.
func (_u *FinalReportUpdate) RemoveNotificationDeliveries(v ...*ReportNotificationDelivery) *FinalReportUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNotificationDeliveryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FinalReportUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FinalReportUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FinalReportUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FinalReportUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *FinalReportUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(finalreport.Table, finalreport.Columns, sqlgraph.NewFieldSpec(finalreport.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(finalreport.FieldModel, field.TypeString)
	}
	if _u.mutation.OutputModeCleared() {
		_spec.ClearField(finalreport.FieldOutputMode, field.TypeString)
	}
	if _u.mutation.CreatedByWorkflowCleared() {
		_spec.ClearField(finalreport.FieldCreatedByWorkflow, field.TypeString)
	}
	if _u.mutation.SubReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   finalreport.SubReportsTable,
			Columns: finalreport.SubReportsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subreport.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubReportsIDs(); len(nodes) > 0 && !_u.mutation.SubReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   finalreport.SubReportsTable,
			Columns: finalreport.SubReportsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subreport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   finalreport.SubReportsTable,
			Columns: finalreport.SubReportsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subreport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NotificationDeliveriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   finalreport.NotificationDeliveriesTable,
			Columns: []string{finalreport.NotificationDeliveriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportnotificationdelivery.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotificationDeliveriesIDs(); len(nodes) > 0 && !_u.mutation.NotificationDeliveriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   finalreport.NotificationDeliveriesTable,
			Columns: []string{finalreport.NotificationDeliveriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportnotificationdelivery.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotificationDeliveriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   finalreport.NotificationDeliveriesTable,
			Columns: []string{finalreport.NotificationDeliveriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportnotificationdelivery.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{finalreport.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FinalReportUpdateOne is the builder for updating a single FinalReport entity.
type FinalReportUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FinalReportMutation
}

// AddSubReportIDs adds the "sub_reports" edge to the SubReport entity by IDs.
func (_u *FinalReportUpdateOne) AddSubReportIDs(ids ...int) *FinalReportUpdateOne {
	_u.mutation.AddSubReportIDs(ids...)
	return _u
}

// AddSubReports adds the "sub_reports" edges to the SubReport entity.
func (_u *FinalReportUpdateOne) AddSubReports(v ...*SubReport) *FinalReportUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubReportIDs(ids...)
}

// AddNotificationDeliveryIDs adds the "notification_deliveries" edge to the ReportNotificationDelivery entity by IDs.
func (_u *FinalReportUpdateOne) AddNotificationDeliveryIDs(ids ...int) *FinalReportUpdateOne {
	_u.mutation.AddNotificationDeliveryIDs(ids...)
	return _u
}

// AddNotificationDeliveries adds the "notification_deliveries" edges to the ReportNotificationDelivery entity.
func (_u *FinalReportUpdateOne) AddNotificationDeliveries(v ...*ReportNotificationDelivery) *FinalReportUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNotificationDeliveryIDs(ids...)
}

// Mutation returns the FinalReportMutation object of the builder.
func (_u *FinalReportUpdateOne) Mutation() *FinalReportMutation {
	return _u.mutation
}

// ClearSubReports clears all "sub_reports" edges to the SubReport entity.
func (_u *FinalReportUpdateOne) ClearSubReports() *FinalReportUpdateOne {
	_u.mutation.ClearSubReports()
	return _u
}

// RemoveSubReportIDs removes the "sub_reports" edge to SubReport entities by IDs.
func (_u *FinalReportUpdateOne) RemoveSubReportIDs(ids ...int) *FinalReportUpdateOne {
	_u.mutation.RemoveSubReportIDs(ids...)
	return _u
}

// RemoveSubReports removes "sub_reports" edges to SubReport entities.
func (_u *FinalReportUpdateOne) RemoveSubReports(v ...*SubReport) *FinalReportUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubReportIDs(ids...)
}

// ClearNotificationDeliveries clears all "notification_deliveries" edges to the ReportNotificationDelivery entity.
func (_u *FinalReportUpdateOne) ClearNotificationDeliveries() *FinalReportUpdateOne {
	_u.mutation.ClearNotificationDeliveries()
	return _u
}

// RemoveNotificationDeliveryIDs removes the "notification_deliveries" edge to ReportNotificationDelivery entities by IDs.
func (_u *FinalReportUpdateOne) RemoveNotificationDeliveryIDs(ids ...int) *FinalReportUpdateOne {
	_u.mutation.RemoveNotificationDeliveryIDs(ids...)
	return _u
}

// RemoveNotificationDeliveries removes "notification_deliveries" edges to ReportNotificationDelivery entities.
func (_u *FinalReportUpdateOne) RemoveNotificationDeliveries(v ...*ReportNotificationDelivery) *FinalReportUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNotificationDeliveryIDs(ids...)
}

// Where appends a list predicates to the FinalReportUpdate builder.
func (_u *FinalReportUpdateOne) Where(ps ...predicate.FinalReport) *FinalReportUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FinalReportUpdateOne) Select(field string, fields ...string) *FinalReportUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FinalReport entity.
func (_u *FinalReportUpdateOne) Save(ctx context.Context) (*FinalReport, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FinalReportUpdateOne) SaveX(ctx context.Context) *FinalReport {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FinalReportUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FinalReportUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *FinalReportUpdateOne) sqlSave(ctx context.Context) (_node *FinalReport, err error) {
	_spec := sqlgraph.NewUpdateSpec(finalreport.Table, finalreport.Columns, sqlgraph.NewFieldSpec(finalreport.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FinalReport.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, finalreport.FieldID)
		for _, f := range fields {
			if !finalreport.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != finalreport.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(finalreport.FieldModel, field.TypeString)
	}
	if _u.mutation.OutputModeCleared() {
		_spec.ClearField(finalreport.FieldOutputMode, field.TypeString)
	}
	if _u.mutation.CreatedByWorkflowCleared() {
		_spec.ClearField(finalreport.FieldCreatedByWorkflow, field.TypeString)
	}
	if _u.mutation.SubReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   finalreport.SubReportsTable,
			Columns: finalreport.SubReportsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subreport.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubReportsIDs(); len(nodes) > 0 && !_u.mutation.SubReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   finalreport.SubReportsTable,
			Columns: finalreport.SubReportsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subreport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   finalreport.SubReportsTable,
			Columns: finalreport.SubReportsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subreport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NotificationDeliveriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   finalreport.NotificationDeliveriesTable,
			Columns: []string{finalreport.NotificationDeliveriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportnotificationdelivery.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNotificationDeliveriesIDs(); len(nodes) > 0 && !_u.mutation.NotificationDeliveriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   finalreport.NotificationDeliveriesTable,
			Columns: []string{finalreport.NotificationDeliveriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportnotificationdelivery.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NotificationDeliveriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   finalreport.NotificationDeliveriesTable,
			Columns: []string{finalreport.NotificationDeliveriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reportnotificationdelivery.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FinalReport{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{finalreport.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
