// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/openclarion/openclarion/internal/persistence/ent/finalreport"
	"github.com/openclarion/openclarion/internal/persistence/ent/tenant"
)

// FinalReport is the model entity for the FinalReport schema.
type FinalReport struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// tenant owning this row; assigned from authenticated operation context
	TenantID int `json:"tenant_id,omitempty"`
	// business correlation key for the reduced incident/window
	CorrelationKey string `json:"correlation_key,omitempty"`
	// activity idempotency key for final report generation
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// operator-facing title extracted from validated JSON
	Title string `json:"title,omitempty"`
	// operator-facing executive summary extracted from validated JSON
	ExecutiveSummary string `json:"executive_summary,omitempty"`
	// "info" | "warning" | "critical"
	Severity string `json:"severity,omitempty"`
	// "low" | "medium" | "high"
	Confidence string `json:"confidence,omitempty"`
	// validated sub_reports projection from the FinalReport JSON
	SubreportSummaries json.RawMessage `json:"subreport_summaries,omitempty"`
	// validated recommended_actions array from the FinalReport JSON
	RecommendedActions json.RawMessage `json:"recommended_actions,omitempty"`
	// operator-facing notification body to send after persistence succeeds
	NotificationText string `json:"notification_text,omitempty"`
	// full accepted FinalReport JSON payload
	Content json.RawMessage `json:"content,omitempty"`
	// provider model that produced the accepted output
	Model string `json:"model,omitempty"`
	// provider output mode: "json_schema" | "json_object"
	OutputMode string `json:"output_mode,omitempty"`
	// temporal workflow id that produced this final report
	CreatedByWorkflow string `json:"created_by_workflow,omitempty"`
	// server-side report persistence timestamp
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FinalReportQuery when eager-loading is set.
	Edges        FinalReportEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FinalReportEdges holds the relations/edges for other nodes in the graph.
type FinalReportEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// SubReports holds the value of the sub_reports edge.
	SubReports []*SubReport `json:"sub_reports,omitempty"`
	// NotificationDeliveries holds the value of the notification_deliveries edge.
	NotificationDeliveries []*ReportNotificationDelivery `json:"notification_deliveries,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FinalReportEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// SubReportsOrErr returns the SubReports value or an error if the edge
// was not loaded in eager-loading.
func (e FinalReportEdges) SubReportsOrErr() ([]*SubReport, error) {
	if e.loadedTypes[1] {
		return e.SubReports, nil
	}
	return nil, &NotLoadedError{edge: "sub_reports"}
}

// NotificationDeliveriesOrErr returns the NotificationDeliveries value or an error if the edge
// was not loaded in eager-loading.
func (e FinalReportEdges) NotificationDeliveriesOrErr() ([]*ReportNotificationDelivery, error) {
	if e.loadedTypes[2] {
		return e.NotificationDeliveries, nil
	}
	return nil, &NotLoadedError{edge: "notification_deliveries"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FinalReport) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case finalreport.FieldSubreportSummaries, finalreport.FieldRecommendedActions, finalreport.FieldContent:
			values[i] = new([]byte)
		case finalreport.FieldID, finalreport.FieldTenantID:
			values[i] = new(sql.NullInt64)
		case finalreport.FieldCorrelationKey, finalreport.FieldIdempotencyKey, finalreport.FieldTitle, finalreport.FieldExecutiveSummary, finalreport.FieldSeverity, finalreport.FieldConfidence, finalreport.FieldNotificationText, finalreport.FieldModel, finalreport.FieldOutputMode, finalreport.FieldCreatedByWorkflow:
			values[i] = new(sql.NullString)
		case finalreport.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FinalReport fields.
func (_m *FinalReport) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case finalreport.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case finalreport.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = int(value.Int64)
			}
		case finalreport.FieldCorrelationKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field correlation_key", values[i])
			} else if value.Valid {
				_m.CorrelationKey = value.String
			}
		case finalreport.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = value.String
			}
		case finalreport.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case finalreport.FieldExecutiveSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field executive_summary", values[i])
			} else if value.Valid {
				_m.ExecutiveSummary = value.String
			}
		case finalreport.FieldSeverity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field severity", values[i])
			} else if value.Valid {
				_m.Severity = value.String
			}
		case finalreport.FieldConfidence:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field confidence", values[i])
			} else if value.Valid {
				_m.Confidence = value.String
			}
		case finalreport.FieldSubreportSummaries:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field subreport_summaries", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SubreportSummaries); err != nil {
					return fmt.Errorf("unmarshal field subreport_summaries: %w", err)
				}
			}
		case finalreport.FieldRecommendedActions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field recommended_actions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RecommendedActions); err != nil {
					return fmt.Errorf("unmarshal field recommended_actions: %w", err)
				}
			}
		case finalreport.FieldNotificationText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notification_text", values[i])
			} else if value.Valid {
				_m.NotificationText = value.String
			}
		case finalreport.FieldContent:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Content); err != nil {
					return fmt.Errorf("unmarshal field content: %w", err)
				}
			}
		case finalreport.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case finalreport.FieldOutputMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field output_mode", values[i])
			} else if value.Valid {
				_m.OutputMode = value.String
			}
		case finalreport.FieldCreatedByWorkflow:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_workflow", values[i])
			} else if value.Valid {
				_m.CreatedByWorkflow = value.String
			}
		case finalreport.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FinalReport.
// This includes values selected through modifiers, order, etc.
func (_m *FinalReport) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the FinalReport entity.
func (_m *FinalReport) QueryTenant() *TenantQuery {
	return NewFinalReportClient(_m.config).QueryTenant(_m)
}

// QuerySubReports queries the "sub_reports" edge of the FinalReport entity.
func (_m *FinalReport) QuerySubReports() *SubReportQuery {
	return NewFinalReportClient(_m.config).QuerySubReports(_m)
}

// QueryNotificationDeliveries queries the "notification_deliveries" edge of the FinalReport entity.
func (_m *FinalReport) QueryNotificationDeliveries() *ReportNotificationDeliveryQuery {
	return NewFinalReportClient(_m.config).QueryNotificationDeliveries(_m)
}

// Update returns a builder for updating this FinalReport.
// Note that you need to call FinalReport.Unwrap() before calling this method if this FinalReport
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FinalReport) Update() *FinalReportUpdateOne {
	return NewFinalReportClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FinalReport entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FinalReport) Unwrap() *FinalReport {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FinalReport is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FinalReport) String() string {
	var builder strings.Builder
	builder.WriteString("FinalReport(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("correlation_key=")
	builder.WriteString(_m.CorrelationKey)
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(_m.IdempotencyKey)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("executive_summary=")
	builder.WriteString(_m.ExecutiveSummary)
	builder.WriteString(", ")
	builder.WriteString("severity=")
	builder.WriteString(_m.Severity)
	builder.WriteString(", ")
	builder.WriteString("confidence=")
	builder.WriteString(_m.Confidence)
	builder.WriteString(", ")
	builder.WriteString("subreport_summaries=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubreportSummaries))
	builder.WriteString(", ")
	builder.WriteString("recommended_actions=")
	builder.WriteString(fmt.Sprintf("%v", _m.RecommendedActions))
	builder.WriteString(", ")
	builder.WriteString("notification_text=")
	builder.WriteString(_m.NotificationText)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(fmt.Sprintf("%v", _m.Content))
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("output_mode=")
	builder.WriteString(_m.OutputMode)
	builder.WriteString(", ")
	builder.WriteString("created_by_workflow=")
	builder.WriteString(_m.CreatedByWorkflow)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// FinalReports is a parsable slice of FinalReport.
type FinalReports []*FinalReport
