// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/openclarion/openclarion/internal/persistence/ent/notificationchanneltestproof"
	"github.com/openclarion/openclarion/internal/persistence/ent/predicate"
)

// NotificationChannelTestProofDelete is the builder for deleting a NotificationChannelTestProof entity.
type NotificationChannelTestProofDelete struct {
	config
	hooks    []Hook
	mutation *NotificationChannelTestProofMutation
}

// Where appends a list predicates to the NotificationChannelTestProofDelete builder.
func (_d *NotificationChannelTestProofDelete) Where(ps ...predicate.NotificationChannelTestProof) *NotificationChannelTestProofDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *NotificationChannelTestProofDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NotificationChannelTestProofDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *NotificationChannelTestProofDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(notificationchanneltestproof.Table, sqlgraph.NewFieldSpec(notificationchanneltestproof.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// NotificationChannelTestProofDeleteOne is the builder for deleting a single NotificationChannelTestProof entity.
type NotificationChannelTestProofDeleteOne struct {
	_d *NotificationChannelTestProofDelete
}

// Where appends a list predicates to the NotificationChannelTestProofDelete builder.
func (_d *NotificationChannelTestProofDeleteOne) Where(ps ...predicate.NotificationChannelTestProof) *NotificationChannelTestProofDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *NotificationChannelTestProofDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{notificationchanneltestproof.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NotificationChannelTestProofDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
