// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/openclarion/openclarion/internal/persistence/ent/notificationchannelprofile"
	"github.com/openclarion/openclarion/internal/persistence/ent/notificationchanneltestproof"
	"github.com/openclarion/openclarion/internal/persistence/ent/predicate"
)

// NotificationChannelProfileUpdate is the builder for updating NotificationChannelProfile entities.
type NotificationChannelProfileUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationChannelProfileMutation
}

// Where appends a list predicates to the NotificationChannelProfileUpdate builder.
func (_u *NotificationChannelProfileUpdate) Where(ps ...predicate.NotificationChannelProfile) *NotificationChannelProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *NotificationChannelProfileUpdate) SetName(v string) *NotificationChannelProfileUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NotificationChannelProfileUpdate) SetNillableName(v *string) *NotificationChannelProfileUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *NotificationChannelProfileUpdate) SetKind(v string) *NotificationChannelProfileUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *NotificationChannelProfileUpdate) SetNillableKind(v *string) *NotificationChannelProfileUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetSecretRef sets the "secret_ref" field.
func (_u *NotificationChannelProfileUpdate) SetSecretRef(v string) *NotificationChannelProfileUpdate {
	_u.mutation.SetSecretRef(v)
	return _u
}

// SetNillableSecretRef sets the "secret_ref" field if the given value is not nil.
func (_u *NotificationChannelProfileUpdate) SetNillableSecretRef(v *string) *NotificationChannelProfileUpdate {
	if v != nil {
		_u.SetSecretRef(*v)
	}
	return _u
}

// SetDeliveryScopes sets the "delivery_scopes" field.
func (_u *NotificationChannelProfileUpdate) SetDeliveryScopes(v []string) *NotificationChannelProfileUpdate {
	_u.mutation.SetDeliveryScopes(v)
	return _u
}

// AppendDeliveryScopes appends value to the "delivery_scopes" field.
func (_u *NotificationChannelProfileUpdate) AppendDeliveryScopes(v []string) *NotificationChannelProfileUpdate {
	_u.mutation.AppendDeliveryScopes(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NotificationChannelProfileUpdate) SetEnabled(v bool) *NotificationChannelProfileUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NotificationChannelProfileUpdate) SetNillableEnabled(v *bool) *NotificationChannelProfileUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetLabels sets the "labels" field.
func (_u *NotificationChannelProfileUpdate) SetLabels(v map[string]string) *NotificationChannelProfileUpdate {
	_u.mutation.SetLabels(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationChannelProfileUpdate) SetUpdatedAt(v time.Time) *NotificationChannelProfileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTestProofIDs adds the "test_proofs" edge to the NotificationChannelTestProof entity by IDs.
func (_u *NotificationChannelProfileUpdate) AddTestProofIDs(ids ...int) *NotificationChannelProfileUpdate {
	_u.mutation.AddTestProofIDs(ids...)
	return _u
}

// AddTestProofs adds the "test_proofs" edges to the NotificationChannelTestProof entity.
func (_u *NotificationChannelProfileUpdate) AddTestProofs(v ...*NotificationChannelTestProof) *NotificationChannelProfileUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTestProofIDs(ids...)
}

// Mutation returns the NotificationChannelProfileMutation object of the builder.
func (_u *NotificationChannelProfileUpdate) Mutation() *NotificationChannelProfileMutation {
	return _u.mutation
}

// ClearTestProofs clears all "test_proofs" edges to the NotificationChannelTestProof entity.
func (_u *NotificationChannelProfileUpdate) ClearTestProofs() *NotificationChannelProfileUpdate {
	_u.mutation.ClearTestProofs()
	return _u
}

// RemoveTestProofIDs removes the "test_proofs" edge to NotificationChannelTestProof entities by IDs.
func (_u *NotificationChannelProfileUpdate) RemoveTestProofIDs(ids ...int) *NotificationChannelProfileUpdate {
	_u.mutation.RemoveTestProofIDs(ids...)
	return _u
}

// RemoveTestProofs removes "test_proofs" edges to NotificationChannelTestProof entities.
func (_u *NotificationChannelProfileUpdate) RemoveTestProofs(v ...*NotificationChannelTestProof) *NotificationChannelProfileUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTestProofIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationChannelProfileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationChannelProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationChannelProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationChannelProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotificationChannelProfileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := notificationchannelprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationChannelProfileUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := notificationchannelprofile.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "NotificationChannelProfile.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := notificationchannelprofile.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "NotificationChannelProfile.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SecretRef(); ok {
		if err := notificationchannelprofile.SecretRefValidator(v); err != nil {
			return &ValidationError{Name: "secret_ref", err: fmt.Errorf(`ent: validator failed for field "NotificationChannelProfile.secret_ref": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotificationChannelProfile.tenant"`)
	}
	return nil
}

func (_u *NotificationChannelProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationchannelprofile.Table, notificationchannelprofile.Columns, sqlgraph.NewFieldSpec(notificationchannelprofile.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(notificationchannelprofile.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(notificationchannelprofile.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecretRef(); ok {
		_spec.SetField(notificationchannelprofile.FieldSecretRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeliveryScopes(); ok {
		_spec.SetField(notificationchannelprofile.FieldDeliveryScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDeliveryScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, notificationchannelprofile.FieldDeliveryScopes, value)
		})
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(notificationchannelprofile.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(notificationchannelprofile.FieldLabels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationchannelprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TestProofsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationchannelprofile.TestProofsTable,
			Columns: []string{notificationchannelprofile.TestProofsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationchanneltestproof.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTestProofsIDs(); len(nodes) > 0 && !_u.mutation.TestProofsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationchannelprofile.TestProofsTable,
			Columns: []string{notificationchannelprofile.TestProofsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationchanneltestproof.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TestProofsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationchannelprofile.TestProofsTable,
			Columns: []string{notificationchannelprofile.TestProofsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationchanneltestproof.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationchannelprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationChannelProfileUpdateOne is the builder for updating a single NotificationChannelProfile entity.
type NotificationChannelProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationChannelProfileMutation
}

// SetName sets the "name" field.
func (_u *NotificationChannelProfileUpdateOne) SetName(v string) *NotificationChannelProfileUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NotificationChannelProfileUpdateOne) SetNillableName(v *string) *NotificationChannelProfileUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *NotificationChannelProfileUpdateOne) SetKind(v string) *NotificationChannelProfileUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *NotificationChannelProfileUpdateOne) SetNillableKind(v *string) *NotificationChannelProfileUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetSecretRef sets the "secret_ref" field.
func (_u *NotificationChannelProfileUpdateOne) SetSecretRef(v string) *NotificationChannelProfileUpdateOne {
	_u.mutation.SetSecretRef(v)
	return _u
}

// SetNillableSecretRef sets the "secret_ref" field if the given value is not nil.
func (_u *NotificationChannelProfileUpdateOne) SetNillableSecretRef(v *string) *NotificationChannelProfileUpdateOne {
	if v != nil {
		_u.SetSecretRef(*v)
	}
	return _u
}

// SetDeliveryScopes sets the "delivery_scopes" field.
func (_u *NotificationChannelProfileUpdateOne) SetDeliveryScopes(v []string) *NotificationChannelProfileUpdateOne {
	_u.mutation.SetDeliveryScopes(v)
	return _u
}

// AppendDeliveryScopes appends value to the "delivery_scopes" field.
func (_u *NotificationChannelProfileUpdateOne) AppendDeliveryScopes(v []string) *NotificationChannelProfileUpdateOne {
	_u.mutation.AppendDeliveryScopes(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NotificationChannelProfileUpdateOne) SetEnabled(v bool) *NotificationChannelProfileUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NotificationChannelProfileUpdateOne) SetNillableEnabled(v *bool) *NotificationChannelProfileUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetLabels sets the "labels" field.
func (_u *NotificationChannelProfileUpdateOne) SetLabels(v map[string]string) *NotificationChannelProfileUpdateOne {
	_u.mutation.SetLabels(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationChannelProfileUpdateOne) SetUpdatedAt(v time.Time) *NotificationChannelProfileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTestProofIDs adds the "test_proofs" edge to the NotificationChannelTestProof entity by IDs.
func (_u *NotificationChannelProfileUpdateOne) AddTestProofIDs(ids ...int) *NotificationChannelProfileUpdateOne {
	_u.mutation.AddTestProofIDs(ids...)
	return _u
}

// AddTestProofs adds the "test_proofs" edges to the NotificationChannelTestProof entity.
func (_u *NotificationChannelProfileUpdateOne) AddTestProofs(v ...*NotificationChannelTestProof) *NotificationChannelProfileUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTestProofIDs(ids...)
}

// Mutation returns the NotificationChannelProfileMutation object of the builder.
func (_u *NotificationChannelProfileUpdateOne) Mutation() *NotificationChannelProfileMutation {
	return _u.mutation
}

// ClearTestProofs clears all "test_proofs" edges to the NotificationChannelTestProof entity.
func (_u *NotificationChannelProfileUpdateOne) ClearTestProofs() *NotificationChannelProfileUpdateOne {
	_u.mutation.ClearTestProofs()
	return _u
}

// RemoveTestProofIDs removes the "test_proofs" edge to NotificationChannelTestProof entities by IDs.
func (_u *NotificationChannelProfileUpdateOne) RemoveTestProofIDs(ids ...int) *NotificationChannelProfileUpdateOne {
	_u.mutation.RemoveTestProofIDs(ids...)
	return _u
}

// RemoveTestProofs removes "test_proofs" edges to NotificationChannelTestProof entities.
func (_u *NotificationChannelProfileUpdateOne) RemoveTestProofs(v ...*NotificationChannelTestProof) *NotificationChannelProfileUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTestProofIDs(ids...)
}

// Where appends a list predicates to the NotificationChannelProfileUpdate builder.
func (_u *NotificationChannelProfileUpdateOne) Where(ps ...predicate.NotificationChannelProfile) *NotificationChannelProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationChannelProfileUpdateOne) Select(field string, fields ...string) *NotificationChannelProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NotificationChannelProfile entity.
func (_u *NotificationChannelProfileUpdateOne) Save(ctx context.Context) (*NotificationChannelProfile, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationChannelProfileUpdateOne) SaveX(ctx context.Context) *NotificationChannelProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationChannelProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationChannelProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotificationChannelProfileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := notificationchannelprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationChannelProfileUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := notificationchannelprofile.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "NotificationChannelProfile.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := notificationchannelprofile.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "NotificationChannelProfile.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SecretRef(); ok {
		if err := notificationchannelprofile.SecretRefValidator(v); err != nil {
			return &ValidationError{Name: "secret_ref", err: fmt.Errorf(`ent: validator failed for field "NotificationChannelProfile.secret_ref": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotificationChannelProfile.tenant"`)
	}
	return nil
}

func (_u *NotificationChannelProfileUpdateOne) sqlSave(ctx context.Context) (_node *NotificationChannelProfile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationchannelprofile.Table, notificationchannelprofile.Columns, sqlgraph.NewFieldSpec(notificationchannelprofile.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotificationChannelProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notificationchannelprofile.FieldID)
		for _, f := range fields {
			if !notificationchannelprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notificationchannelprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(notificationchannelprofile.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(notificationchannelprofile.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecretRef(); ok {
		_spec.SetField(notificationchannelprofile.FieldSecretRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeliveryScopes(); ok {
		_spec.SetField(notificationchannelprofile.FieldDeliveryScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDeliveryScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, notificationchannelprofile.FieldDeliveryScopes, value)
		})
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(notificationchannelprofile.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(notificationchannelprofile.FieldLabels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationchannelprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TestProofsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationchannelprofile.TestProofsTable,
			Columns: []string{notificationchannelprofile.TestProofsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationchanneltestproof.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTestProofsIDs(); len(nodes) > 0 && !_u.mutation.TestProofsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationchannelprofile.TestProofsTable,
			Columns: []string{notificationchannelprofile.TestProofsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationchanneltestproof.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TestProofsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notificationchannelprofile.TestProofsTable,
			Columns: []string{notificationchannelprofile.TestProofsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationchanneltestproof.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &NotificationChannelProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationchannelprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
