// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/openclarion/openclarion/internal/persistence/ent/notificationchannelprofile"
)

// NotificationChannelProfileCreate is the builder for creating a NotificationChannelProfile entity.
type NotificationChannelProfileCreate struct {
	config
	mutation *NotificationChannelProfileMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *NotificationChannelProfileCreate) SetName(v string) *NotificationChannelProfileCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *NotificationChannelProfileCreate) SetKind(v string) *NotificationChannelProfileCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *NotificationChannelProfileCreate) SetNillableKind(v *string) *NotificationChannelProfileCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetSecretRef sets the "secret_ref" field.
func (_c *NotificationChannelProfileCreate) SetSecretRef(v string) *NotificationChannelProfileCreate {
	_c.mutation.SetSecretRef(v)
	return _c
}

// SetDeliveryScopes sets the "delivery_scopes" field.
func (_c *NotificationChannelProfileCreate) SetDeliveryScopes(v []string) *NotificationChannelProfileCreate {
	_c.mutation.SetDeliveryScopes(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *NotificationChannelProfileCreate) SetEnabled(v bool) *NotificationChannelProfileCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *NotificationChannelProfileCreate) SetNillableEnabled(v *bool) *NotificationChannelProfileCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetLabels sets the "labels" field.
func (_c *NotificationChannelProfileCreate) SetLabels(v map[string]string) *NotificationChannelProfileCreate {
	_c.mutation.SetLabels(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NotificationChannelProfileCreate) SetCreatedAt(v time.Time) *NotificationChannelProfileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NotificationChannelProfileCreate) SetNillableCreatedAt(v *time.Time) *NotificationChannelProfileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NotificationChannelProfileCreate) SetUpdatedAt(v time.Time) *NotificationChannelProfileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *NotificationChannelProfileCreate) SetNillableUpdatedAt(v *time.Time) *NotificationChannelProfileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the NotificationChannelProfileMutation object of the builder.
func (_c *NotificationChannelProfileCreate) Mutation() *NotificationChannelProfileMutation {
	return _c.mutation
}

// Save creates the NotificationChannelProfile in the database.
func (_c *NotificationChannelProfileCreate) Save(ctx context.Context) (*NotificationChannelProfile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationChannelProfileCreate) SaveX(ctx context.Context) *NotificationChannelProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationChannelProfileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationChannelProfileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotificationChannelProfileCreate) defaults() {
	if _, ok := _c.mutation.Kind(); !ok {
		v := notificationchannelprofile.DefaultKind
		_c.mutation.SetKind(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := notificationchannelprofile.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := notificationchannelprofile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := notificationchannelprofile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationChannelProfileCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "NotificationChannelProfile.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := notificationchannelprofile.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "NotificationChannelProfile.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "NotificationChannelProfile.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := notificationchannelprofile.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "NotificationChannelProfile.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SecretRef(); !ok {
		return &ValidationError{Name: "secret_ref", err: errors.New(`ent: missing required field "NotificationChannelProfile.secret_ref"`)}
	}
	if v, ok := _c.mutation.SecretRef(); ok {
		if err := notificationchannelprofile.SecretRefValidator(v); err != nil {
			return &ValidationError{Name: "secret_ref", err: fmt.Errorf(`ent: validator failed for field "NotificationChannelProfile.secret_ref": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeliveryScopes(); !ok {
		return &ValidationError{Name: "delivery_scopes", err: errors.New(`ent: missing required field "NotificationChannelProfile.delivery_scopes"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "NotificationChannelProfile.enabled"`)}
	}
	if _, ok := _c.mutation.Labels(); !ok {
		return &ValidationError{Name: "labels", err: errors.New(`ent: missing required field "NotificationChannelProfile.labels"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NotificationChannelProfile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "NotificationChannelProfile.updated_at"`)}
	}
	return nil
}

func (_c *NotificationChannelProfileCreate) sqlSave(ctx context.Context) (*NotificationChannelProfile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationChannelProfileCreate) createSpec() (*NotificationChannelProfile, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationChannelProfile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notificationchannelprofile.Table, sqlgraph.NewFieldSpec(notificationchannelprofile.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(notificationchannelprofile.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(notificationchannelprofile.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.SecretRef(); ok {
		_spec.SetField(notificationchannelprofile.FieldSecretRef, field.TypeString, value)
		_node.SecretRef = value
	}
	if value, ok := _c.mutation.DeliveryScopes(); ok {
		_spec.SetField(notificationchannelprofile.FieldDeliveryScopes, field.TypeJSON, value)
		_node.DeliveryScopes = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(notificationchannelprofile.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Labels(); ok {
		_spec.SetField(notificationchannelprofile.FieldLabels, field.TypeJSON, value)
		_node.Labels = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(notificationchannelprofile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationchannelprofile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotificationChannelProfile.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotificationChannelProfileUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *NotificationChannelProfileCreate) OnConflict(opts ...sql.ConflictOption) *NotificationChannelProfileUpsertOne {
	_c.conflict = opts
	return &NotificationChannelProfileUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotificationChannelProfile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NotificationChannelProfileCreate) OnConflictColumns(columns ...string) *NotificationChannelProfileUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NotificationChannelProfileUpsertOne{
		create: _c,
	}
}

type (
	// NotificationChannelProfileUpsertOne is the builder for "upsert"-ing
	//  one NotificationChannelProfile node.
	NotificationChannelProfileUpsertOne struct {
		create *NotificationChannelProfileCreate
	}

	// NotificationChannelProfileUpsert is the "OnConflict" setter.
	NotificationChannelProfileUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *NotificationChannelProfileUpsert) SetName(v string) *NotificationChannelProfileUpsert {
	u.Set(notificationchannelprofile.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *NotificationChannelProfileUpsert) UpdateName() *NotificationChannelProfileUpsert {
	u.SetExcluded(notificationchannelprofile.FieldName)
	return u
}

// SetKind sets the "kind" field.
func (u *NotificationChannelProfileUpsert) SetKind(v string) *NotificationChannelProfileUpsert {
	u.Set(notificationchannelprofile.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *NotificationChannelProfileUpsert) UpdateKind() *NotificationChannelProfileUpsert {
	u.SetExcluded(notificationchannelprofile.FieldKind)
	return u
}

// SetSecretRef sets the "secret_ref" field.
func (u *NotificationChannelProfileUpsert) SetSecretRef(v string) *NotificationChannelProfileUpsert {
	u.Set(notificationchannelprofile.FieldSecretRef, v)
	return u
}

// UpdateSecretRef sets the "secret_ref" field to the value that was provided on create.
func (u *NotificationChannelProfileUpsert) UpdateSecretRef() *NotificationChannelProfileUpsert {
	u.SetExcluded(notificationchannelprofile.FieldSecretRef)
	return u
}

// SetDeliveryScopes sets the "delivery_scopes" field.
func (u *NotificationChannelProfileUpsert) SetDeliveryScopes(v []string) *NotificationChannelProfileUpsert {
	u.Set(notificationchannelprofile.FieldDeliveryScopes, v)
	return u
}

// UpdateDeliveryScopes sets the "delivery_scopes" field to the value that was provided on create.
func (u *NotificationChannelProfileUpsert) UpdateDeliveryScopes() *NotificationChannelProfileUpsert {
	u.SetExcluded(notificationchannelprofile.FieldDeliveryScopes)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *NotificationChannelProfileUpsert) SetEnabled(v bool) *NotificationChannelProfileUpsert {
	u.Set(notificationchannelprofile.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *NotificationChannelProfileUpsert) UpdateEnabled() *NotificationChannelProfileUpsert {
	u.SetExcluded(notificationchannelprofile.FieldEnabled)
	return u
}

// SetLabels sets the "labels" field.
func (u *NotificationChannelProfileUpsert) SetLabels(v map[string]string) *NotificationChannelProfileUpsert {
	u.Set(notificationchannelprofile.FieldLabels, v)
	return u
}

// UpdateLabels sets the "labels" field to the value that was provided on create.
func (u *NotificationChannelProfileUpsert) UpdateLabels() *NotificationChannelProfileUpsert {
	u.SetExcluded(notificationchannelprofile.FieldLabels)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NotificationChannelProfileUpsert) SetUpdatedAt(v time.Time) *NotificationChannelProfileUpsert {
	u.Set(notificationchannelprofile.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NotificationChannelProfileUpsert) UpdateUpdatedAt() *NotificationChannelProfileUpsert {
	u.SetExcluded(notificationchannelprofile.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.NotificationChannelProfile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NotificationChannelProfileUpsertOne) UpdateNewValues() *NotificationChannelProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(notificationchannelprofile.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotificationChannelProfile.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NotificationChannelProfileUpsertOne) Ignore() *NotificationChannelProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotificationChannelProfileUpsertOne) DoNothing() *NotificationChannelProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotificationChannelProfileCreate.OnConflict
// documentation for more info.
func (u *NotificationChannelProfileUpsertOne) Update(set func(*NotificationChannelProfileUpsert)) *NotificationChannelProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotificationChannelProfileUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *NotificationChannelProfileUpsertOne) SetName(v string) *NotificationChannelProfileUpsertOne {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *NotificationChannelProfileUpsertOne) UpdateName() *NotificationChannelProfileUpsertOne {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.UpdateName()
	})
}

// SetKind sets the "kind" field.
func (u *NotificationChannelProfileUpsertOne) SetKind(v string) *NotificationChannelProfileUpsertOne {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *NotificationChannelProfileUpsertOne) UpdateKind() *NotificationChannelProfileUpsertOne {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.UpdateKind()
	})
}

// SetSecretRef sets the "secret_ref" field.
func (u *NotificationChannelProfileUpsertOne) SetSecretRef(v string) *NotificationChannelProfileUpsertOne {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.SetSecretRef(v)
	})
}

// UpdateSecretRef sets the "secret_ref" field to the value that was provided on create.
func (u *NotificationChannelProfileUpsertOne) UpdateSecretRef() *NotificationChannelProfileUpsertOne {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.UpdateSecretRef()
	})
}

// SetDeliveryScopes sets the "delivery_scopes" field.
func (u *NotificationChannelProfileUpsertOne) SetDeliveryScopes(v []string) *NotificationChannelProfileUpsertOne {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.SetDeliveryScopes(v)
	})
}

// UpdateDeliveryScopes sets the "delivery_scopes" field to the value that was provided on create.
func (u *NotificationChannelProfileUpsertOne) UpdateDeliveryScopes() *NotificationChannelProfileUpsertOne {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.UpdateDeliveryScopes()
	})
}

// SetEnabled sets the "enabled" field.
func (u *NotificationChannelProfileUpsertOne) SetEnabled(v bool) *NotificationChannelProfileUpsertOne {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *NotificationChannelProfileUpsertOne) UpdateEnabled() *NotificationChannelProfileUpsertOne {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.UpdateEnabled()
	})
}

// SetLabels sets the "labels" field.
func (u *NotificationChannelProfileUpsertOne) SetLabels(v map[string]string) *NotificationChannelProfileUpsertOne {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.SetLabels(v)
	})
}

// UpdateLabels sets the "labels" field to the value that was provided on create.
func (u *NotificationChannelProfileUpsertOne) UpdateLabels() *NotificationChannelProfileUpsertOne {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.UpdateLabels()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NotificationChannelProfileUpsertOne) SetUpdatedAt(v time.Time) *NotificationChannelProfileUpsertOne {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NotificationChannelProfileUpsertOne) UpdateUpdatedAt() *NotificationChannelProfileUpsertOne {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *NotificationChannelProfileUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotificationChannelProfileCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotificationChannelProfileUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NotificationChannelProfileUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NotificationChannelProfileUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NotificationChannelProfileCreateBulk is the builder for creating many NotificationChannelProfile entities in bulk.
type NotificationChannelProfileCreateBulk struct {
	config
	err      error
	builders []*NotificationChannelProfileCreate
	conflict []sql.ConflictOption
}

// Save creates the NotificationChannelProfile entities in the database.
func (_c *NotificationChannelProfileCreateBulk) Save(ctx context.Context) ([]*NotificationChannelProfile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NotificationChannelProfile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationChannelProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationChannelProfileCreateBulk) SaveX(ctx context.Context) []*NotificationChannelProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationChannelProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationChannelProfileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotificationChannelProfile.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotificationChannelProfileUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *NotificationChannelProfileCreateBulk) OnConflict(opts ...sql.ConflictOption) *NotificationChannelProfileUpsertBulk {
	_c.conflict = opts
	return &NotificationChannelProfileUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotificationChannelProfile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NotificationChannelProfileCreateBulk) OnConflictColumns(columns ...string) *NotificationChannelProfileUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NotificationChannelProfileUpsertBulk{
		create: _c,
	}
}

// NotificationChannelProfileUpsertBulk is the builder for "upsert"-ing
// a bulk of NotificationChannelProfile nodes.
type NotificationChannelProfileUpsertBulk struct {
	create *NotificationChannelProfileCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NotificationChannelProfile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NotificationChannelProfileUpsertBulk) UpdateNewValues() *NotificationChannelProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(notificationchannelprofile.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotificationChannelProfile.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NotificationChannelProfileUpsertBulk) Ignore() *NotificationChannelProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotificationChannelProfileUpsertBulk) DoNothing() *NotificationChannelProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotificationChannelProfileCreateBulk.OnConflict
// documentation for more info.
func (u *NotificationChannelProfileUpsertBulk) Update(set func(*NotificationChannelProfileUpsert)) *NotificationChannelProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotificationChannelProfileUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *NotificationChannelProfileUpsertBulk) SetName(v string) *NotificationChannelProfileUpsertBulk {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *NotificationChannelProfileUpsertBulk) UpdateName() *NotificationChannelProfileUpsertBulk {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.UpdateName()
	})
}

// SetKind sets the "kind" field.
func (u *NotificationChannelProfileUpsertBulk) SetKind(v string) *NotificationChannelProfileUpsertBulk {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *NotificationChannelProfileUpsertBulk) UpdateKind() *NotificationChannelProfileUpsertBulk {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.UpdateKind()
	})
}

// SetSecretRef sets the "secret_ref" field.
func (u *NotificationChannelProfileUpsertBulk) SetSecretRef(v string) *NotificationChannelProfileUpsertBulk {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.SetSecretRef(v)
	})
}

// UpdateSecretRef sets the "secret_ref" field to the value that was provided on create.
func (u *NotificationChannelProfileUpsertBulk) UpdateSecretRef() *NotificationChannelProfileUpsertBulk {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.UpdateSecretRef()
	})
}

// SetDeliveryScopes sets the "delivery_scopes" field.
func (u *NotificationChannelProfileUpsertBulk) SetDeliveryScopes(v []string) *NotificationChannelProfileUpsertBulk {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.SetDeliveryScopes(v)
	})
}

// UpdateDeliveryScopes sets the "delivery_scopes" field to the value that was provided on create.
func (u *NotificationChannelProfileUpsertBulk) UpdateDeliveryScopes() *NotificationChannelProfileUpsertBulk {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.UpdateDeliveryScopes()
	})
}

// SetEnabled sets the "enabled" field.
func (u *NotificationChannelProfileUpsertBulk) SetEnabled(v bool) *NotificationChannelProfileUpsertBulk {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *NotificationChannelProfileUpsertBulk) UpdateEnabled() *NotificationChannelProfileUpsertBulk {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.UpdateEnabled()
	})
}

// SetLabels sets the "labels" field.
func (u *NotificationChannelProfileUpsertBulk) SetLabels(v map[string]string) *NotificationChannelProfileUpsertBulk {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.SetLabels(v)
	})
}

// UpdateLabels sets the "labels" field to the value that was provided on create.
func (u *NotificationChannelProfileUpsertBulk) UpdateLabels() *NotificationChannelProfileUpsertBulk {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.UpdateLabels()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NotificationChannelProfileUpsertBulk) SetUpdatedAt(v time.Time) *NotificationChannelProfileUpsertBulk {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NotificationChannelProfileUpsertBulk) UpdateUpdatedAt() *NotificationChannelProfileUpsertBulk {
	return u.Update(func(s *NotificationChannelProfileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *NotificationChannelProfileUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NotificationChannelProfileCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotificationChannelProfileCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotificationChannelProfileUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
