// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/openclarion/openclarion/internal/persistence/ent/rbacassignment"
	"github.com/openclarion/openclarion/internal/persistence/ent/tenant"
)

// RBACAssignment is the model entity for the RBACAssignment schema.
type RBACAssignment struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// tenant owning this row; assigned from authenticated operation context
	TenantID int `json:"tenant_id,omitempty"`
	// "user" or "department"
	SubjectKind string `json:"subject_kind,omitempty"`
	// IAM subject or local directory department key
	SubjectKey string `json:"subject_key,omitempty"`
	// local OpenClarion role such as "admin", "operator", "leader", "responder", or "viewer"
	Role string `json:"role,omitempty"`
	// OpenClarion resource family covered by the role assignment
	ScopeKind string `json:"scope_kind,omitempty"`
	// resource identifier within scope_kind; empty only for global scope
	ScopeKey string `json:"scope_key,omitempty"`
	// whether this role assignment is active
	Enabled bool `json:"enabled,omitempty"`
	// authenticated subject that created the assignment
	CreatedBy string `json:"created_by,omitempty"`
	// authenticated subject that last mutated the assignment
	UpdatedBy string `json:"updated_by,omitempty"`
	// server-side assignment creation timestamp
	CreatedAt time.Time `json:"created_at,omitempty"`
	// server-side last-mutation timestamp
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RBACAssignmentQuery when eager-loading is set.
	Edges        RBACAssignmentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RBACAssignmentEdges holds the relations/edges for other nodes in the graph.
type RBACAssignmentEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RBACAssignmentEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RBACAssignment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rbacassignment.FieldEnabled:
			values[i] = new(sql.NullBool)
		case rbacassignment.FieldID, rbacassignment.FieldTenantID:
			values[i] = new(sql.NullInt64)
		case rbacassignment.FieldSubjectKind, rbacassignment.FieldSubjectKey, rbacassignment.FieldRole, rbacassignment.FieldScopeKind, rbacassignment.FieldScopeKey, rbacassignment.FieldCreatedBy, rbacassignment.FieldUpdatedBy:
			values[i] = new(sql.NullString)
		case rbacassignment.FieldCreatedAt, rbacassignment.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RBACAssignment fields.
func (_m *RBACAssignment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rbacassignment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case rbacassignment.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = int(value.Int64)
			}
		case rbacassignment.FieldSubjectKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject_kind", values[i])
			} else if value.Valid {
				_m.SubjectKind = value.String
			}
		case rbacassignment.FieldSubjectKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject_key", values[i])
			} else if value.Valid {
				_m.SubjectKey = value.String
			}
		case rbacassignment.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case rbacassignment.FieldScopeKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope_kind", values[i])
			} else if value.Valid {
				_m.ScopeKind = value.String
			}
		case rbacassignment.FieldScopeKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope_key", values[i])
			} else if value.Valid {
				_m.ScopeKey = value.String
			}
		case rbacassignment.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case rbacassignment.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case rbacassignment.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.String
			}
		case rbacassignment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case rbacassignment.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RBACAssignment.
// This includes values selected through modifiers, order, etc.
func (_m *RBACAssignment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the RBACAssignment entity.
func (_m *RBACAssignment) QueryTenant() *TenantQuery {
	return NewRBACAssignmentClient(_m.config).QueryTenant(_m)
}

// Update returns a builder for updating this RBACAssignment.
// Note that you need to call RBACAssignment.Unwrap() before calling this method if this RBACAssignment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RBACAssignment) Update() *RBACAssignmentUpdateOne {
	return NewRBACAssignmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RBACAssignment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RBACAssignment) Unwrap() *RBACAssignment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RBACAssignment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RBACAssignment) String() string {
	var builder strings.Builder
	builder.WriteString("RBACAssignment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("subject_kind=")
	builder.WriteString(_m.SubjectKind)
	builder.WriteString(", ")
	builder.WriteString("subject_key=")
	builder.WriteString(_m.SubjectKey)
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("scope_kind=")
	builder.WriteString(_m.ScopeKind)
	builder.WriteString(", ")
	builder.WriteString("scope_key=")
	builder.WriteString(_m.ScopeKey)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(_m.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RBACAssignments is a parsable slice of RBACAssignment.
type RBACAssignments []*RBACAssignment
