// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/openclarion/openclarion/internal/persistence/ent/predicate"
	"github.com/openclarion/openclarion/internal/persistence/ent/rbacassignment"
)

// RBACAssignmentDelete is the builder for deleting a RBACAssignment entity.
type RBACAssignmentDelete struct {
	config
	hooks    []Hook
	mutation *RBACAssignmentMutation
}

// Where appends a list predicates to the RBACAssignmentDelete builder.
func (_d *RBACAssignmentDelete) Where(ps ...predicate.RBACAssignment) *RBACAssignmentDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RBACAssignmentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RBACAssignmentDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RBACAssignmentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(rbacassignment.Table, sqlgraph.NewFieldSpec(rbacassignment.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RBACAssignmentDeleteOne is the builder for deleting a single RBACAssignment entity.
type RBACAssignmentDeleteOne struct {
	_d *RBACAssignmentDelete
}

// Where appends a list predicates to the RBACAssignmentDelete builder.
func (_d *RBACAssignmentDeleteOne) Where(ps ...predicate.RBACAssignment) *RBACAssignmentDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RBACAssignmentDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{rbacassignment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RBACAssignmentDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
