// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/openclarion/openclarion/internal/persistence/ent/predicate"
	"github.com/openclarion/openclarion/internal/persistence/ent/reportnotificationdelivery"
)

// ReportNotificationDeliveryUpdate is the builder for updating ReportNotificationDelivery entities.
type ReportNotificationDeliveryUpdate struct {
	config
	hooks    []Hook
	mutation *ReportNotificationDeliveryMutation
}

// Where appends a list predicates to the ReportNotificationDeliveryUpdate builder.
func (_u *ReportNotificationDeliveryUpdate) Where(ps ...predicate.ReportNotificationDelivery) *ReportNotificationDeliveryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetReportNotificationChannelProfileID sets the "report_notification_channel_profile_id" field.
func (_u *ReportNotificationDeliveryUpdate) SetReportNotificationChannelProfileID(v int) *ReportNotificationDeliveryUpdate {
	_u.mutation.ResetReportNotificationChannelProfileID()
	_u.mutation.SetReportNotificationChannelProfileID(v)
	return _u
}

// SetNillableReportNotificationChannelProfileID sets the "report_notification_channel_profile_id" field if the given value is not nil.
func (_u *ReportNotificationDeliveryUpdate) SetNillableReportNotificationChannelProfileID(v *int) *ReportNotificationDeliveryUpdate {
	if v != nil {
		_u.SetReportNotificationChannelProfileID(*v)
	}
	return _u
}

// AddReportNotificationChannelProfileID adds value to the "report_notification_channel_profile_id" field.
func (_u *ReportNotificationDeliveryUpdate) AddReportNotificationChannelProfileID(v int) *ReportNotificationDeliveryUpdate {
	_u.mutation.AddReportNotificationChannelProfileID(v)
	return _u
}

// ClearReportNotificationChannelProfileID clears the value of the "report_notification_channel_profile_id" field.
func (_u *ReportNotificationDeliveryUpdate) ClearReportNotificationChannelProfileID() *ReportNotificationDeliveryUpdate {
	_u.mutation.ClearReportNotificationChannelProfileID()
	return _u
}

// SetProviderMessageID sets the "provider_message_id" field.
func (_u *ReportNotificationDeliveryUpdate) SetProviderMessageID(v string) *ReportNotificationDeliveryUpdate {
	_u.mutation.SetProviderMessageID(v)
	return _u
}

// SetNillableProviderMessageID sets the "provider_message_id" field if the given value is not nil.
func (_u *ReportNotificationDeliveryUpdate) SetNillableProviderMessageID(v *string) *ReportNotificationDeliveryUpdate {
	if v != nil {
		_u.SetProviderMessageID(*v)
	}
	return _u
}

// ClearProviderMessageID clears the value of the "provider_message_id" field.
func (_u *ReportNotificationDeliveryUpdate) ClearProviderMessageID() *ReportNotificationDeliveryUpdate {
	_u.mutation.ClearProviderMessageID()
	return _u
}

// SetProviderStatus sets the "provider_status" field.
func (_u *ReportNotificationDeliveryUpdate) SetProviderStatus(v string) *ReportNotificationDeliveryUpdate {
	_u.mutation.SetProviderStatus(v)
	return _u
}

// SetNillableProviderStatus sets the "provider_status" field if the given value is not nil.
func (_u *ReportNotificationDeliveryUpdate) SetNillableProviderStatus(v *string) *ReportNotificationDeliveryUpdate {
	if v != nil {
		_u.SetProviderStatus(*v)
	}
	return _u
}

// ClearProviderStatus clears the value of the "provider_status" field.
func (_u *ReportNotificationDeliveryUpdate) ClearProviderStatus() *ReportNotificationDeliveryUpdate {
	_u.mutation.ClearProviderStatus()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReportNotificationDeliveryUpdate) SetStatus(v string) *ReportNotificationDeliveryUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReportNotificationDeliveryUpdate) SetNillableStatus(v *string) *ReportNotificationDeliveryUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRaw sets the "raw" field.
func (_u *ReportNotificationDeliveryUpdate) SetRaw(v json.RawMessage) *ReportNotificationDeliveryUpdate {
	_u.mutation.SetRaw(v)
	return _u
}

// AppendRaw appends value to the "raw" field.
func (_u *ReportNotificationDeliveryUpdate) AppendRaw(v json.RawMessage) *ReportNotificationDeliveryUpdate {
	_u.mutation.AppendRaw(v)
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *ReportNotificationDeliveryUpdate) SetFailureReason(v string) *ReportNotificationDeliveryUpdate {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *ReportNotificationDeliveryUpdate) SetNillableFailureReason(v *string) *ReportNotificationDeliveryUpdate {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *ReportNotificationDeliveryUpdate) ClearFailureReason() *ReportNotificationDeliveryUpdate {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetDeliveredAt sets the "delivered_at" field.
func (_u *ReportNotificationDeliveryUpdate) SetDeliveredAt(v time.Time) *ReportNotificationDeliveryUpdate {
	_u.mutation.SetDeliveredAt(v)
	return _u
}

// SetNillableDeliveredAt sets the "delivered_at" field if the given value is not nil.
func (_u *ReportNotificationDeliveryUpdate) SetNillableDeliveredAt(v *time.Time) *ReportNotificationDeliveryUpdate {
	if v != nil {
		_u.SetDeliveredAt(*v)
	}
	return _u
}

// ClearDeliveredAt clears the value of the "delivered_at" field.
func (_u *ReportNotificationDeliveryUpdate) ClearDeliveredAt() *ReportNotificationDeliveryUpdate {
	_u.mutation.ClearDeliveredAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReportNotificationDeliveryUpdate) SetUpdatedAt(v time.Time) *ReportNotificationDeliveryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ReportNotificationDeliveryMutation object of the builder.
func (_u *ReportNotificationDeliveryUpdate) Mutation() *ReportNotificationDeliveryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReportNotificationDeliveryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReportNotificationDeliveryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReportNotificationDeliveryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReportNotificationDeliveryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReportNotificationDeliveryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := reportnotificationdelivery.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReportNotificationDeliveryUpdate) check() error {
	if v, ok := _u.mutation.ProviderMessageID(); ok {
		if err := reportnotificationdelivery.ProviderMessageIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_message_id", err: fmt.Errorf(`ent: validator failed for field "ReportNotificationDelivery.provider_message_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderStatus(); ok {
		if err := reportnotificationdelivery.ProviderStatusValidator(v); err != nil {
			return &ValidationError{Name: "provider_status", err: fmt.Errorf(`ent: validator failed for field "ReportNotificationDelivery.provider_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := reportnotificationdelivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReportNotificationDelivery.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FailureReason(); ok {
		if err := reportnotificationdelivery.FailureReasonValidator(v); err != nil {
			return &ValidationError{Name: "failure_reason", err: fmt.Errorf(`ent: validator failed for field "ReportNotificationDelivery.failure_reason": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReportNotificationDelivery.tenant"`)
	}
	if _u.mutation.FinalReportCleared() && len(_u.mutation.FinalReportIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReportNotificationDelivery.final_report"`)
	}
	return nil
}

func (_u *ReportNotificationDeliveryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reportnotificationdelivery.Table, reportnotificationdelivery.Columns, sqlgraph.NewFieldSpec(reportnotificationdelivery.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReportNotificationChannelProfileID(); ok {
		_spec.SetField(reportnotificationdelivery.FieldReportNotificationChannelProfileID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReportNotificationChannelProfileID(); ok {
		_spec.AddField(reportnotificationdelivery.FieldReportNotificationChannelProfileID, field.TypeInt, value)
	}
	if _u.mutation.ReportNotificationChannelProfileIDCleared() {
		_spec.ClearField(reportnotificationdelivery.FieldReportNotificationChannelProfileID, field.TypeInt)
	}
	if value, ok := _u.mutation.ProviderMessageID(); ok {
		_spec.SetField(reportnotificationdelivery.FieldProviderMessageID, field.TypeString, value)
	}
	if _u.mutation.ProviderMessageIDCleared() {
		_spec.ClearField(reportnotificationdelivery.FieldProviderMessageID, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderStatus(); ok {
		_spec.SetField(reportnotificationdelivery.FieldProviderStatus, field.TypeString, value)
	}
	if _u.mutation.ProviderStatusCleared() {
		_spec.ClearField(reportnotificationdelivery.FieldProviderStatus, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(reportnotificationdelivery.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Raw(); ok {
		_spec.SetField(reportnotificationdelivery.FieldRaw, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRaw(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, reportnotificationdelivery.FieldRaw, value)
		})
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(reportnotificationdelivery.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(reportnotificationdelivery.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.DeliveredAt(); ok {
		_spec.SetField(reportnotificationdelivery.FieldDeliveredAt, field.TypeTime, value)
	}
	if _u.mutation.DeliveredAtCleared() {
		_spec.ClearField(reportnotificationdelivery.FieldDeliveredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(reportnotificationdelivery.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reportnotificationdelivery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReportNotificationDeliveryUpdateOne is the builder for updating a single ReportNotificationDelivery entity.
type ReportNotificationDeliveryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReportNotificationDeliveryMutation
}

// SetReportNotificationChannelProfileID sets the "report_notification_channel_profile_id" field.
func (_u *ReportNotificationDeliveryUpdateOne) SetReportNotificationChannelProfileID(v int) *ReportNotificationDeliveryUpdateOne {
	_u.mutation.ResetReportNotificationChannelProfileID()
	_u.mutation.SetReportNotificationChannelProfileID(v)
	return _u
}

// SetNillableReportNotificationChannelProfileID sets the "report_notification_channel_profile_id" field if the given value is not nil.
func (_u *ReportNotificationDeliveryUpdateOne) SetNillableReportNotificationChannelProfileID(v *int) *ReportNotificationDeliveryUpdateOne {
	if v != nil {
		_u.SetReportNotificationChannelProfileID(*v)
	}
	return _u
}

// AddReportNotificationChannelProfileID adds value to the "report_notification_channel_profile_id" field.
func (_u *ReportNotificationDeliveryUpdateOne) AddReportNotificationChannelProfileID(v int) *ReportNotificationDeliveryUpdateOne {
	_u.mutation.AddReportNotificationChannelProfileID(v)
	return _u
}

// ClearReportNotificationChannelProfileID clears the value of the "report_notification_channel_profile_id" field.
func (_u *ReportNotificationDeliveryUpdateOne) ClearReportNotificationChannelProfileID() *ReportNotificationDeliveryUpdateOne {
	_u.mutation.ClearReportNotificationChannelProfileID()
	return _u
}

// SetProviderMessageID sets the "provider_message_id" field.
func (_u *ReportNotificationDeliveryUpdateOne) SetProviderMessageID(v string) *ReportNotificationDeliveryUpdateOne {
	_u.mutation.SetProviderMessageID(v)
	return _u
}

// SetNillableProviderMessageID sets the "provider_message_id" field if the given value is not nil.
func (_u *ReportNotificationDeliveryUpdateOne) SetNillableProviderMessageID(v *string) *ReportNotificationDeliveryUpdateOne {
	if v != nil {
		_u.SetProviderMessageID(*v)
	}
	return _u
}

// ClearProviderMessageID clears the value of the "provider_message_id" field.
func (_u *ReportNotificationDeliveryUpdateOne) ClearProviderMessageID() *ReportNotificationDeliveryUpdateOne {
	_u.mutation.ClearProviderMessageID()
	return _u
}

// SetProviderStatus sets the "provider_status" field.
func (_u *ReportNotificationDeliveryUpdateOne) SetProviderStatus(v string) *ReportNotificationDeliveryUpdateOne {
	_u.mutation.SetProviderStatus(v)
	return _u
}

// SetNillableProviderStatus sets the "provider_status" field if the given value is not nil.
func (_u *ReportNotificationDeliveryUpdateOne) SetNillableProviderStatus(v *string) *ReportNotificationDeliveryUpdateOne {
	if v != nil {
		_u.SetProviderStatus(*v)
	}
	return _u
}

// ClearProviderStatus clears the value of the "provider_status" field.
func (_u *ReportNotificationDeliveryUpdateOne) ClearProviderStatus() *ReportNotificationDeliveryUpdateOne {
	_u.mutation.ClearProviderStatus()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReportNotificationDeliveryUpdateOne) SetStatus(v string) *ReportNotificationDeliveryUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReportNotificationDeliveryUpdateOne) SetNillableStatus(v *string) *ReportNotificationDeliveryUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRaw sets the "raw" field.
func (_u *ReportNotificationDeliveryUpdateOne) SetRaw(v json.RawMessage) *ReportNotificationDeliveryUpdateOne {
	_u.mutation.SetRaw(v)
	return _u
}

// AppendRaw appends value to the "raw" field.
func (_u *ReportNotificationDeliveryUpdateOne) AppendRaw(v json.RawMessage) *ReportNotificationDeliveryUpdateOne {
	_u.mutation.AppendRaw(v)
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *ReportNotificationDeliveryUpdateOne) SetFailureReason(v string) *ReportNotificationDeliveryUpdateOne {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *ReportNotificationDeliveryUpdateOne) SetNillableFailureReason(v *string) *ReportNotificationDeliveryUpdateOne {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *ReportNotificationDeliveryUpdateOne) ClearFailureReason() *ReportNotificationDeliveryUpdateOne {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetDeliveredAt sets the "delivered_at" field.
func (_u *ReportNotificationDeliveryUpdateOne) SetDeliveredAt(v time.Time) *ReportNotificationDeliveryUpdateOne {
	_u.mutation.SetDeliveredAt(v)
	return _u
}

// SetNillableDeliveredAt sets the "delivered_at" field if the given value is not nil.
func (_u *ReportNotificationDeliveryUpdateOne) SetNillableDeliveredAt(v *time.Time) *ReportNotificationDeliveryUpdateOne {
	if v != nil {
		_u.SetDeliveredAt(*v)
	}
	return _u
}

// ClearDeliveredAt clears the value of the "delivered_at" field.
func (_u *ReportNotificationDeliveryUpdateOne) ClearDeliveredAt() *ReportNotificationDeliveryUpdateOne {
	_u.mutation.ClearDeliveredAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReportNotificationDeliveryUpdateOne) SetUpdatedAt(v time.Time) *ReportNotificationDeliveryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ReportNotificationDeliveryMutation object of the builder.
func (_u *ReportNotificationDeliveryUpdateOne) Mutation() *ReportNotificationDeliveryMutation {
	return _u.mutation
}

// Where appends a list predicates to the ReportNotificationDeliveryUpdate builder.
func (_u *ReportNotificationDeliveryUpdateOne) Where(ps ...predicate.ReportNotificationDelivery) *ReportNotificationDeliveryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReportNotificationDeliveryUpdateOne) Select(field string, fields ...string) *ReportNotificationDeliveryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReportNotificationDelivery entity.
func (_u *ReportNotificationDeliveryUpdateOne) Save(ctx context.Context) (*ReportNotificationDelivery, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReportNotificationDeliveryUpdateOne) SaveX(ctx context.Context) *ReportNotificationDelivery {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReportNotificationDeliveryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReportNotificationDeliveryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReportNotificationDeliveryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := reportnotificationdelivery.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReportNotificationDeliveryUpdateOne) check() error {
	if v, ok := _u.mutation.ProviderMessageID(); ok {
		if err := reportnotificationdelivery.ProviderMessageIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_message_id", err: fmt.Errorf(`ent: validator failed for field "ReportNotificationDelivery.provider_message_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderStatus(); ok {
		if err := reportnotificationdelivery.ProviderStatusValidator(v); err != nil {
			return &ValidationError{Name: "provider_status", err: fmt.Errorf(`ent: validator failed for field "ReportNotificationDelivery.provider_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := reportnotificationdelivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReportNotificationDelivery.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FailureReason(); ok {
		if err := reportnotificationdelivery.FailureReasonValidator(v); err != nil {
			return &ValidationError{Name: "failure_reason", err: fmt.Errorf(`ent: validator failed for field "ReportNotificationDelivery.failure_reason": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReportNotificationDelivery.tenant"`)
	}
	if _u.mutation.FinalReportCleared() && len(_u.mutation.FinalReportIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReportNotificationDelivery.final_report"`)
	}
	return nil
}

func (_u *ReportNotificationDeliveryUpdateOne) sqlSave(ctx context.Context) (_node *ReportNotificationDelivery, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reportnotificationdelivery.Table, reportnotificationdelivery.Columns, sqlgraph.NewFieldSpec(reportnotificationdelivery.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReportNotificationDelivery.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reportnotificationdelivery.FieldID)
		for _, f := range fields {
			if !reportnotificationdelivery.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != reportnotificationdelivery.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReportNotificationChannelProfileID(); ok {
		_spec.SetField(reportnotificationdelivery.FieldReportNotificationChannelProfileID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReportNotificationChannelProfileID(); ok {
		_spec.AddField(reportnotificationdelivery.FieldReportNotificationChannelProfileID, field.TypeInt, value)
	}
	if _u.mutation.ReportNotificationChannelProfileIDCleared() {
		_spec.ClearField(reportnotificationdelivery.FieldReportNotificationChannelProfileID, field.TypeInt)
	}
	if value, ok := _u.mutation.ProviderMessageID(); ok {
		_spec.SetField(reportnotificationdelivery.FieldProviderMessageID, field.TypeString, value)
	}
	if _u.mutation.ProviderMessageIDCleared() {
		_spec.ClearField(reportnotificationdelivery.FieldProviderMessageID, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderStatus(); ok {
		_spec.SetField(reportnotificationdelivery.FieldProviderStatus, field.TypeString, value)
	}
	if _u.mutation.ProviderStatusCleared() {
		_spec.ClearField(reportnotificationdelivery.FieldProviderStatus, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(reportnotificationdelivery.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Raw(); ok {
		_spec.SetField(reportnotificationdelivery.FieldRaw, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRaw(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, reportnotificationdelivery.FieldRaw, value)
		})
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(reportnotificationdelivery.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(reportnotificationdelivery.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.DeliveredAt(); ok {
		_spec.SetField(reportnotificationdelivery.FieldDeliveredAt, field.TypeTime, value)
	}
	if _u.mutation.DeliveredAtCleared() {
		_spec.ClearField(reportnotificationdelivery.FieldDeliveredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(reportnotificationdelivery.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ReportNotificationDelivery{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reportnotificationdelivery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
