// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/openclarion/openclarion/internal/persistence/ent/finalreport"
	"github.com/openclarion/openclarion/internal/persistence/ent/predicate"
	"github.com/openclarion/openclarion/internal/persistence/ent/subreport"
)

// SubReportUpdate is the builder for updating SubReport entities.
type SubReportUpdate struct {
	config
	hooks    []Hook
	mutation *SubReportMutation
}

// Where appends a list predicates to the SubReportUpdate builder.
func (_u *SubReportUpdate) Where(ps ...predicate.SubReport) *SubReportUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// AddFinalReportIDs adds the "final_reports" edge to the FinalReport entity by IDs.
func (_u *SubReportUpdate) AddFinalReportIDs(ids ...int) *SubReportUpdate {
	_u.mutation.AddFinalReportIDs(ids...)
	return _u
}

// AddFinalReports adds the "final_reports" edges to the FinalReport entity.
func (_u *SubReportUpdate) AddFinalReports(v ...*FinalReport) *SubReportUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFinalReportIDs(ids...)
}

// Mutation returns the SubReportMutation object of the builder.
func (_u *SubReportUpdate) Mutation() *SubReportMutation {
	return _u.mutation
}

// ClearFinalReports clears all "final_reports" edges to the FinalReport entity.
func (_u *SubReportUpdate) ClearFinalReports() *SubReportUpdate {
	_u.mutation.ClearFinalReports()
	return _u
}

// RemoveFinalReportIDs removes the "final_reports" edge to FinalReport entities by IDs.
func (_u *SubReportUpdate) RemoveFinalReportIDs(ids ...int) *SubReportUpdate {
	_u.mutation.RemoveFinalReportIDs(ids...)
	return _u
}

// RemoveFinalReports removes "final_reports" edges to FinalReport entities.
func (_u *SubReportUpdate) RemoveFinalReports(v ...*FinalReport) *SubReportUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFinalReportIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubReportUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubReportUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubReportUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubReportUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubReportUpdate) check() error {
	if _u.mutation.SnapshotCleared() && len(_u.mutation.SnapshotIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubReport.snapshot"`)
	}
	return nil
}

func (_u *SubReportUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subreport.Table, subreport.Columns, sqlgraph.NewFieldSpec(subreport.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(subreport.FieldModel, field.TypeString)
	}
	if _u.mutation.OutputModeCleared() {
		_spec.ClearField(subreport.FieldOutputMode, field.TypeString)
	}
	if _u.mutation.CreatedByWorkflowCleared() {
		_spec.ClearField(subreport.FieldCreatedByWorkflow, field.TypeString)
	}
	if _u.mutation.FinalReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   subreport.FinalReportsTable,
			Columns: subreport.FinalReportsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(finalreport.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFinalReportsIDs(); len(nodes) > 0 && !_u.mutation.FinalReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   subreport.FinalReportsTable,
			Columns: subreport.FinalReportsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(finalreport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FinalReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   subreport.FinalReportsTable,
			Columns: subreport.FinalReportsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(finalreport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subreport.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubReportUpdateOne is the builder for updating a single SubReport entity.
type SubReportUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubReportMutation
}

// AddFinalReportIDs adds the "final_reports" edge to the FinalReport entity by IDs.
func (_u *SubReportUpdateOne) AddFinalReportIDs(ids ...int) *SubReportUpdateOne {
	_u.mutation.AddFinalReportIDs(ids...)
	return _u
}

// AddFinalReports adds the "final_reports" edges to the FinalReport entity.
func (_u *SubReportUpdateOne) AddFinalReports(v ...*FinalReport) *SubReportUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFinalReportIDs(ids...)
}

// Mutation returns the SubReportMutation object of the builder.
func (_u *SubReportUpdateOne) Mutation() *SubReportMutation {
	return _u.mutation
}

// ClearFinalReports clears all "final_reports" edges to the FinalReport entity.
func (_u *SubReportUpdateOne) ClearFinalReports() *SubReportUpdateOne {
	_u.mutation.ClearFinalReports()
	return _u
}

// RemoveFinalReportIDs removes the "final_reports" edge to FinalReport entities by IDs.
func (_u *SubReportUpdateOne) RemoveFinalReportIDs(ids ...int) *SubReportUpdateOne {
	_u.mutation.RemoveFinalReportIDs(ids...)
	return _u
}

// RemoveFinalReports removes "final_reports" edges to FinalReport entities.
func (_u *SubReportUpdateOne) RemoveFinalReports(v ...*FinalReport) *SubReportUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFinalReportIDs(ids...)
}

// Where appends a list predicates to the SubReportUpdate builder.
func (_u *SubReportUpdateOne) Where(ps ...predicate.SubReport) *SubReportUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubReportUpdateOne) Select(field string, fields ...string) *SubReportUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubReport entity.
func (_u *SubReportUpdateOne) Save(ctx context.Context) (*SubReport, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubReportUpdateOne) SaveX(ctx context.Context) *SubReport {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubReportUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubReportUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubReportUpdateOne) check() error {
	if _u.mutation.SnapshotCleared() && len(_u.mutation.SnapshotIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubReport.snapshot"`)
	}
	return nil
}

func (_u *SubReportUpdateOne) sqlSave(ctx context.Context) (_node *SubReport, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subreport.Table, subreport.Columns, sqlgraph.NewFieldSpec(subreport.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubReport.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subreport.FieldID)
		for _, f := range fields {
			if !subreport.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subreport.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(subreport.FieldModel, field.TypeString)
	}
	if _u.mutation.OutputModeCleared() {
		_spec.ClearField(subreport.FieldOutputMode, field.TypeString)
	}
	if _u.mutation.CreatedByWorkflowCleared() {
		_spec.ClearField(subreport.FieldCreatedByWorkflow, field.TypeString)
	}
	if _u.mutation.FinalReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   subreport.FinalReportsTable,
			Columns: subreport.FinalReportsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(finalreport.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFinalReportsIDs(); len(nodes) > 0 && !_u.mutation.FinalReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   subreport.FinalReportsTable,
			Columns: subreport.FinalReportsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(finalreport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FinalReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   subreport.FinalReportsTable,
			Columns: subreport.FinalReportsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(finalreport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubReport{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subreport.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
