// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/openclarion/openclarion/internal/persistence/ent/evidencesnapshot"
	"github.com/openclarion/openclarion/internal/persistence/ent/finalreport"
	"github.com/openclarion/openclarion/internal/persistence/ent/subreport"
)

// SubReportCreate is the builder for creating a SubReport entity.
type SubReportCreate struct {
	config
	mutation *SubReportMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetEvidenceSnapshotID sets the "evidence_snapshot_id" field.
func (_c *SubReportCreate) SetEvidenceSnapshotID(v int) *SubReportCreate {
	_c.mutation.SetEvidenceSnapshotID(v)
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *SubReportCreate) SetIdempotencyKey(v string) *SubReportCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetScenario sets the "scenario" field.
func (_c *SubReportCreate) SetScenario(v string) *SubReportCreate {
	_c.mutation.SetScenario(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *SubReportCreate) SetTitle(v string) *SubReportCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetSummary sets the "summary" field.
func (_c *SubReportCreate) SetSummary(v string) *SubReportCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetSeverity sets the "severity" field.
func (_c *SubReportCreate) SetSeverity(v string) *SubReportCreate {
	_c.mutation.SetSeverity(v)
	return _c
}

// SetConfidence sets the "confidence" field.
func (_c *SubReportCreate) SetConfidence(v string) *SubReportCreate {
	_c.mutation.SetConfidence(v)
	return _c
}

// SetFindings sets the "findings" field.
func (_c *SubReportCreate) SetFindings(v json.RawMessage) *SubReportCreate {
	_c.mutation.SetFindings(v)
	return _c
}

// SetRecommendedActions sets the "recommended_actions" field.
func (_c *SubReportCreate) SetRecommendedActions(v json.RawMessage) *SubReportCreate {
	_c.mutation.SetRecommendedActions(v)
	return _c
}

// SetEvidenceRefs sets the "evidence_refs" field.
func (_c *SubReportCreate) SetEvidenceRefs(v []string) *SubReportCreate {
	_c.mutation.SetEvidenceRefs(v)
	return _c
}

// SetRetrievalRefs sets the "retrieval_refs" field.
func (_c *SubReportCreate) SetRetrievalRefs(v []string) *SubReportCreate {
	_c.mutation.SetRetrievalRefs(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *SubReportCreate) SetContent(v json.RawMessage) *SubReportCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *SubReportCreate) SetModel(v string) *SubReportCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *SubReportCreate) SetNillableModel(v *string) *SubReportCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetOutputMode sets the "output_mode" field.
func (_c *SubReportCreate) SetOutputMode(v string) *SubReportCreate {
	_c.mutation.SetOutputMode(v)
	return _c
}

// SetNillableOutputMode sets the "output_mode" field if the given value is not nil.
func (_c *SubReportCreate) SetNillableOutputMode(v *string) *SubReportCreate {
	if v != nil {
		_c.SetOutputMode(*v)
	}
	return _c
}

// SetCreatedByWorkflow sets the "created_by_workflow" field.
func (_c *SubReportCreate) SetCreatedByWorkflow(v string) *SubReportCreate {
	_c.mutation.SetCreatedByWorkflow(v)
	return _c
}

// SetNillableCreatedByWorkflow sets the "created_by_workflow" field if the given value is not nil.
func (_c *SubReportCreate) SetNillableCreatedByWorkflow(v *string) *SubReportCreate {
	if v != nil {
		_c.SetCreatedByWorkflow(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubReportCreate) SetCreatedAt(v time.Time) *SubReportCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubReportCreate) SetNillableCreatedAt(v *time.Time) *SubReportCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetSnapshotID sets the "snapshot" edge to the EvidenceSnapshot entity by ID.
func (_c *SubReportCreate) SetSnapshotID(id int) *SubReportCreate {
	_c.mutation.SetSnapshotID(id)
	return _c
}

// SetSnapshot sets the "snapshot" edge to the EvidenceSnapshot entity.
func (_c *SubReportCreate) SetSnapshot(v *EvidenceSnapshot) *SubReportCreate {
	return _c.SetSnapshotID(v.ID)
}

// AddFinalReportIDs adds the "final_reports" edge to the FinalReport entity by IDs.
func (_c *SubReportCreate) AddFinalReportIDs(ids ...int) *SubReportCreate {
	_c.mutation.AddFinalReportIDs(ids...)
	return _c
}

// AddFinalReports adds the "final_reports" edges to the FinalReport entity.
func (_c *SubReportCreate) AddFinalReports(v ...*FinalReport) *SubReportCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFinalReportIDs(ids...)
}

// Mutation returns the SubReportMutation object of the builder.
func (_c *SubReportCreate) Mutation() *SubReportMutation {
	return _c.mutation
}

// Save creates the SubReport in the database.
func (_c *SubReportCreate) Save(ctx context.Context) (*SubReport, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubReportCreate) SaveX(ctx context.Context) *SubReport {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubReportCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubReportCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubReportCreate) defaults() {
	if _, ok := _c.mutation.RetrievalRefs(); !ok {
		v := subreport.DefaultRetrievalRefs
		_c.mutation.SetRetrievalRefs(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subreport.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubReportCreate) check() error {
	if _, ok := _c.mutation.EvidenceSnapshotID(); !ok {
		return &ValidationError{Name: "evidence_snapshot_id", err: errors.New(`ent: missing required field "SubReport.evidence_snapshot_id"`)}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "SubReport.idempotency_key"`)}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := subreport.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "SubReport.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scenario(); !ok {
		return &ValidationError{Name: "scenario", err: errors.New(`ent: missing required field "SubReport.scenario"`)}
	}
	if v, ok := _c.mutation.Scenario(); ok {
		if err := subreport.ScenarioValidator(v); err != nil {
			return &ValidationError{Name: "scenario", err: fmt.Errorf(`ent: validator failed for field "SubReport.scenario": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "SubReport.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := subreport.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "SubReport.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Summary(); !ok {
		return &ValidationError{Name: "summary", err: errors.New(`ent: missing required field "SubReport.summary"`)}
	}
	if v, ok := _c.mutation.Summary(); ok {
		if err := subreport.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "SubReport.summary": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Severity(); !ok {
		return &ValidationError{Name: "severity", err: errors.New(`ent: missing required field "SubReport.severity"`)}
	}
	if v, ok := _c.mutation.Severity(); ok {
		if err := subreport.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "SubReport.severity": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Confidence(); !ok {
		return &ValidationError{Name: "confidence", err: errors.New(`ent: missing required field "SubReport.confidence"`)}
	}
	if v, ok := _c.mutation.Confidence(); ok {
		if err := subreport.ConfidenceValidator(v); err != nil {
			return &ValidationError{Name: "confidence", err: fmt.Errorf(`ent: validator failed for field "SubReport.confidence": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Findings(); !ok {
		return &ValidationError{Name: "findings", err: errors.New(`ent: missing required field "SubReport.findings"`)}
	}
	if _, ok := _c.mutation.RecommendedActions(); !ok {
		return &ValidationError{Name: "recommended_actions", err: errors.New(`ent: missing required field "SubReport.recommended_actions"`)}
	}
	if _, ok := _c.mutation.EvidenceRefs(); !ok {
		return &ValidationError{Name: "evidence_refs", err: errors.New(`ent: missing required field "SubReport.evidence_refs"`)}
	}
	if _, ok := _c.mutation.RetrievalRefs(); !ok {
		return &ValidationError{Name: "retrieval_refs", err: errors.New(`ent: missing required field "SubReport.retrieval_refs"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "SubReport.content"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := subreport.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "SubReport.model": %w`, err)}
		}
	}
	if v, ok := _c.mutation.OutputMode(); ok {
		if err := subreport.OutputModeValidator(v); err != nil {
			return &ValidationError{Name: "output_mode", err: fmt.Errorf(`ent: validator failed for field "SubReport.output_mode": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CreatedByWorkflow(); ok {
		if err := subreport.CreatedByWorkflowValidator(v); err != nil {
			return &ValidationError{Name: "created_by_workflow", err: fmt.Errorf(`ent: validator failed for field "SubReport.created_by_workflow": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubReport.created_at"`)}
	}
	if len(_c.mutation.SnapshotIDs()) == 0 {
		return &ValidationError{Name: "snapshot", err: errors.New(`ent: missing required edge "SubReport.snapshot"`)}
	}
	return nil
}

func (_c *SubReportCreate) sqlSave(ctx context.Context) (*SubReport, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubReportCreate) createSpec() (*SubReport, *sqlgraph.CreateSpec) {
	var (
		_node = &SubReport{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subreport.Table, sqlgraph.NewFieldSpec(subreport.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(subreport.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.Scenario(); ok {
		_spec.SetField(subreport.FieldScenario, field.TypeString, value)
		_node.Scenario = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(subreport.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(subreport.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.Severity(); ok {
		_spec.SetField(subreport.FieldSeverity, field.TypeString, value)
		_node.Severity = value
	}
	if value, ok := _c.mutation.Confidence(); ok {
		_spec.SetField(subreport.FieldConfidence, field.TypeString, value)
		_node.Confidence = value
	}
	if value, ok := _c.mutation.Findings(); ok {
		_spec.SetField(subreport.FieldFindings, field.TypeJSON, value)
		_node.Findings = value
	}
	if value, ok := _c.mutation.RecommendedActions(); ok {
		_spec.SetField(subreport.FieldRecommendedActions, field.TypeJSON, value)
		_node.RecommendedActions = value
	}
	if value, ok := _c.mutation.EvidenceRefs(); ok {
		_spec.SetField(subreport.FieldEvidenceRefs, field.TypeJSON, value)
		_node.EvidenceRefs = value
	}
	if value, ok := _c.mutation.RetrievalRefs(); ok {
		_spec.SetField(subreport.FieldRetrievalRefs, field.TypeJSON, value)
		_node.RetrievalRefs = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(subreport.FieldContent, field.TypeJSON, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(subreport.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.OutputMode(); ok {
		_spec.SetField(subreport.FieldOutputMode, field.TypeString, value)
		_node.OutputMode = value
	}
	if value, ok := _c.mutation.CreatedByWorkflow(); ok {
		_spec.SetField(subreport.FieldCreatedByWorkflow, field.TypeString, value)
		_node.CreatedByWorkflow = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subreport.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.SnapshotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subreport.SnapshotTable,
			Columns: []string{subreport.SnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(evidencesnapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EvidenceSnapshotID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FinalReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   subreport.FinalReportsTable,
			Columns: subreport.FinalReportsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(finalreport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubReport.Create().
//		SetEvidenceSnapshotID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubReportUpsert) {
//			SetEvidenceSnapshotID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubReportCreate) OnConflict(opts ...sql.ConflictOption) *SubReportUpsertOne {
	_c.conflict = opts
	return &SubReportUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubReport.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubReportCreate) OnConflictColumns(columns ...string) *SubReportUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubReportUpsertOne{
		create: _c,
	}
}

type (
	// SubReportUpsertOne is the builder for "upsert"-ing
	//  one SubReport node.
	SubReportUpsertOne struct {
		create *SubReportCreate
	}

	// SubReportUpsert is the "OnConflict" setter.
	SubReportUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubReport.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubReportUpsertOne) UpdateNewValues() *SubReportUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.EvidenceSnapshotID(); exists {
			s.SetIgnore(subreport.FieldEvidenceSnapshotID)
		}
		if _, exists := u.create.mutation.IdempotencyKey(); exists {
			s.SetIgnore(subreport.FieldIdempotencyKey)
		}
		if _, exists := u.create.mutation.Scenario(); exists {
			s.SetIgnore(subreport.FieldScenario)
		}
		if _, exists := u.create.mutation.Title(); exists {
			s.SetIgnore(subreport.FieldTitle)
		}
		if _, exists := u.create.mutation.Summary(); exists {
			s.SetIgnore(subreport.FieldSummary)
		}
		if _, exists := u.create.mutation.Severity(); exists {
			s.SetIgnore(subreport.FieldSeverity)
		}
		if _, exists := u.create.mutation.Confidence(); exists {
			s.SetIgnore(subreport.FieldConfidence)
		}
		if _, exists := u.create.mutation.Findings(); exists {
			s.SetIgnore(subreport.FieldFindings)
		}
		if _, exists := u.create.mutation.RecommendedActions(); exists {
			s.SetIgnore(subreport.FieldRecommendedActions)
		}
		if _, exists := u.create.mutation.EvidenceRefs(); exists {
			s.SetIgnore(subreport.FieldEvidenceRefs)
		}
		if _, exists := u.create.mutation.RetrievalRefs(); exists {
			s.SetIgnore(subreport.FieldRetrievalRefs)
		}
		if _, exists := u.create.mutation.Content(); exists {
			s.SetIgnore(subreport.FieldContent)
		}
		if _, exists := u.create.mutation.Model(); exists {
			s.SetIgnore(subreport.FieldModel)
		}
		if _, exists := u.create.mutation.OutputMode(); exists {
			s.SetIgnore(subreport.FieldOutputMode)
		}
		if _, exists := u.create.mutation.CreatedByWorkflow(); exists {
			s.SetIgnore(subreport.FieldCreatedByWorkflow)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subreport.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubReport.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubReportUpsertOne) Ignore() *SubReportUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubReportUpsertOne) DoNothing() *SubReportUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubReportCreate.OnConflict
// documentation for more info.
func (u *SubReportUpsertOne) Update(set func(*SubReportUpsert)) *SubReportUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubReportUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *SubReportUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubReportCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubReportUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubReportUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubReportUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubReportCreateBulk is the builder for creating many SubReport entities in bulk.
type SubReportCreateBulk struct {
	config
	err      error
	builders []*SubReportCreate
	conflict []sql.ConflictOption
}

// Save creates the SubReport entities in the database.
func (_c *SubReportCreateBulk) Save(ctx context.Context) ([]*SubReport, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubReport, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubReportMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubReportCreateBulk) SaveX(ctx context.Context) []*SubReport {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubReportCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubReportCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubReport.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubReportUpsert) {
//			SetEvidenceSnapshotID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubReportCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubReportUpsertBulk {
	_c.conflict = opts
	return &SubReportUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubReport.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubReportCreateBulk) OnConflictColumns(columns ...string) *SubReportUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubReportUpsertBulk{
		create: _c,
	}
}

// SubReportUpsertBulk is the builder for "upsert"-ing
// a bulk of SubReport nodes.
type SubReportUpsertBulk struct {
	create *SubReportCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubReport.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubReportUpsertBulk) UpdateNewValues() *SubReportUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.EvidenceSnapshotID(); exists {
				s.SetIgnore(subreport.FieldEvidenceSnapshotID)
			}
			if _, exists := b.mutation.IdempotencyKey(); exists {
				s.SetIgnore(subreport.FieldIdempotencyKey)
			}
			if _, exists := b.mutation.Scenario(); exists {
				s.SetIgnore(subreport.FieldScenario)
			}
			if _, exists := b.mutation.Title(); exists {
				s.SetIgnore(subreport.FieldTitle)
			}
			if _, exists := b.mutation.Summary(); exists {
				s.SetIgnore(subreport.FieldSummary)
			}
			if _, exists := b.mutation.Severity(); exists {
				s.SetIgnore(subreport.FieldSeverity)
			}
			if _, exists := b.mutation.Confidence(); exists {
				s.SetIgnore(subreport.FieldConfidence)
			}
			if _, exists := b.mutation.Findings(); exists {
				s.SetIgnore(subreport.FieldFindings)
			}
			if _, exists := b.mutation.RecommendedActions(); exists {
				s.SetIgnore(subreport.FieldRecommendedActions)
			}
			if _, exists := b.mutation.EvidenceRefs(); exists {
				s.SetIgnore(subreport.FieldEvidenceRefs)
			}
			if _, exists := b.mutation.RetrievalRefs(); exists {
				s.SetIgnore(subreport.FieldRetrievalRefs)
			}
			if _, exists := b.mutation.Content(); exists {
				s.SetIgnore(subreport.FieldContent)
			}
			if _, exists := b.mutation.Model(); exists {
				s.SetIgnore(subreport.FieldModel)
			}
			if _, exists := b.mutation.OutputMode(); exists {
				s.SetIgnore(subreport.FieldOutputMode)
			}
			if _, exists := b.mutation.CreatedByWorkflow(); exists {
				s.SetIgnore(subreport.FieldCreatedByWorkflow)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subreport.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubReport.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubReportUpsertBulk) Ignore() *SubReportUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubReportUpsertBulk) DoNothing() *SubReportUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubReportCreateBulk.OnConflict
// documentation for more info.
func (u *SubReportUpsertBulk) Update(set func(*SubReportUpsert)) *SubReportUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubReportUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *SubReportUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubReportCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubReportCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubReportUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
