// Code generated by ent, DO NOT EDIT.

package directorysyncrun

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/openclarion/openclarion/internal/persistence/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLTE(FieldID, id))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldProvider, v))
}

// PageSize applies equality check predicate on the "page_size" field. It's identical to PageSizeEQ.
func PageSize(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldPageSize, v))
}

// UpdatedAfter applies equality check predicate on the "updated_after" field. It's identical to UpdatedAfterEQ.
func UpdatedAfter(v time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldUpdatedAfter, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldStatus, v))
}

// FailureCode applies equality check predicate on the "failure_code" field. It's identical to FailureCodeEQ.
func FailureCode(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldFailureCode, v))
}

// FailureMessage applies equality check predicate on the "failure_message" field. It's identical to FailureMessageEQ.
func FailureMessage(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldFailureMessage, v))
}

// DepartmentPages applies equality check predicate on the "department_pages" field. It's identical to DepartmentPagesEQ.
func DepartmentPages(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldDepartmentPages, v))
}

// UserPages applies equality check predicate on the "user_pages" field. It's identical to UserPagesEQ.
func UserPages(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldUserPages, v))
}

// DepartmentsUpserted applies equality check predicate on the "departments_upserted" field. It's identical to DepartmentsUpsertedEQ.
func DepartmentsUpserted(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldDepartmentsUpserted, v))
}

// UsersUpserted applies equality check predicate on the "users_upserted" field. It's identical to UsersUpsertedEQ.
func UsersUpserted(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldUsersUpserted, v))
}

// SyncedAt applies equality check predicate on the "synced_at" field. It's identical to SyncedAtEQ.
func SyncedAt(v time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldSyncedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldCreatedAt, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldContainsFold(FieldProvider, v))
}

// PageSizeEQ applies the EQ predicate on the "page_size" field.
func PageSizeEQ(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldPageSize, v))
}

// PageSizeNEQ applies the NEQ predicate on the "page_size" field.
func PageSizeNEQ(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNEQ(FieldPageSize, v))
}

// PageSizeIn applies the In predicate on the "page_size" field.
func PageSizeIn(vs ...int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldIn(FieldPageSize, vs...))
}

// PageSizeNotIn applies the NotIn predicate on the "page_size" field.
func PageSizeNotIn(vs ...int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNotIn(FieldPageSize, vs...))
}

// PageSizeGT applies the GT predicate on the "page_size" field.
func PageSizeGT(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGT(FieldPageSize, v))
}

// PageSizeGTE applies the GTE predicate on the "page_size" field.
func PageSizeGTE(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGTE(FieldPageSize, v))
}

// PageSizeLT applies the LT predicate on the "page_size" field.
func PageSizeLT(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLT(FieldPageSize, v))
}

// PageSizeLTE applies the LTE predicate on the "page_size" field.
func PageSizeLTE(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLTE(FieldPageSize, v))
}

// UpdatedAfterEQ applies the EQ predicate on the "updated_after" field.
func UpdatedAfterEQ(v time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldUpdatedAfter, v))
}

// UpdatedAfterNEQ applies the NEQ predicate on the "updated_after" field.
func UpdatedAfterNEQ(v time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNEQ(FieldUpdatedAfter, v))
}

// UpdatedAfterIn applies the In predicate on the "updated_after" field.
func UpdatedAfterIn(vs ...time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldIn(FieldUpdatedAfter, vs...))
}

// UpdatedAfterNotIn applies the NotIn predicate on the "updated_after" field.
func UpdatedAfterNotIn(vs ...time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNotIn(FieldUpdatedAfter, vs...))
}

// UpdatedAfterGT applies the GT predicate on the "updated_after" field.
func UpdatedAfterGT(v time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGT(FieldUpdatedAfter, v))
}

// UpdatedAfterGTE applies the GTE predicate on the "updated_after" field.
func UpdatedAfterGTE(v time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGTE(FieldUpdatedAfter, v))
}

// UpdatedAfterLT applies the LT predicate on the "updated_after" field.
func UpdatedAfterLT(v time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLT(FieldUpdatedAfter, v))
}

// UpdatedAfterLTE applies the LTE predicate on the "updated_after" field.
func UpdatedAfterLTE(v time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLTE(FieldUpdatedAfter, v))
}

// UpdatedAfterIsNil applies the IsNil predicate on the "updated_after" field.
func UpdatedAfterIsNil() predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldIsNull(FieldUpdatedAfter))
}

// UpdatedAfterNotNil applies the NotNil predicate on the "updated_after" field.
func UpdatedAfterNotNil() predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNotNull(FieldUpdatedAfter))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldContainsFold(FieldStatus, v))
}

// FailureCodeEQ applies the EQ predicate on the "failure_code" field.
func FailureCodeEQ(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldFailureCode, v))
}

// FailureCodeNEQ applies the NEQ predicate on the "failure_code" field.
func FailureCodeNEQ(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNEQ(FieldFailureCode, v))
}

// FailureCodeIn applies the In predicate on the "failure_code" field.
func FailureCodeIn(vs ...string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldIn(FieldFailureCode, vs...))
}

// FailureCodeNotIn applies the NotIn predicate on the "failure_code" field.
func FailureCodeNotIn(vs ...string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNotIn(FieldFailureCode, vs...))
}

// FailureCodeGT applies the GT predicate on the "failure_code" field.
func FailureCodeGT(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGT(FieldFailureCode, v))
}

// FailureCodeGTE applies the GTE predicate on the "failure_code" field.
func FailureCodeGTE(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGTE(FieldFailureCode, v))
}

// FailureCodeLT applies the LT predicate on the "failure_code" field.
func FailureCodeLT(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLT(FieldFailureCode, v))
}

// FailureCodeLTE applies the LTE predicate on the "failure_code" field.
func FailureCodeLTE(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLTE(FieldFailureCode, v))
}

// FailureCodeContains applies the Contains predicate on the "failure_code" field.
func FailureCodeContains(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldContains(FieldFailureCode, v))
}

// FailureCodeHasPrefix applies the HasPrefix predicate on the "failure_code" field.
func FailureCodeHasPrefix(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldHasPrefix(FieldFailureCode, v))
}

// FailureCodeHasSuffix applies the HasSuffix predicate on the "failure_code" field.
func FailureCodeHasSuffix(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldHasSuffix(FieldFailureCode, v))
}

// FailureCodeEqualFold applies the EqualFold predicate on the "failure_code" field.
func FailureCodeEqualFold(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEqualFold(FieldFailureCode, v))
}

// FailureCodeContainsFold applies the ContainsFold predicate on the "failure_code" field.
func FailureCodeContainsFold(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldContainsFold(FieldFailureCode, v))
}

// FailureMessageEQ applies the EQ predicate on the "failure_message" field.
func FailureMessageEQ(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldFailureMessage, v))
}

// FailureMessageNEQ applies the NEQ predicate on the "failure_message" field.
func FailureMessageNEQ(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNEQ(FieldFailureMessage, v))
}

// FailureMessageIn applies the In predicate on the "failure_message" field.
func FailureMessageIn(vs ...string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldIn(FieldFailureMessage, vs...))
}

// FailureMessageNotIn applies the NotIn predicate on the "failure_message" field.
func FailureMessageNotIn(vs ...string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNotIn(FieldFailureMessage, vs...))
}

// FailureMessageGT applies the GT predicate on the "failure_message" field.
func FailureMessageGT(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGT(FieldFailureMessage, v))
}

// FailureMessageGTE applies the GTE predicate on the "failure_message" field.
func FailureMessageGTE(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGTE(FieldFailureMessage, v))
}

// FailureMessageLT applies the LT predicate on the "failure_message" field.
func FailureMessageLT(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLT(FieldFailureMessage, v))
}

// FailureMessageLTE applies the LTE predicate on the "failure_message" field.
func FailureMessageLTE(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLTE(FieldFailureMessage, v))
}

// FailureMessageContains applies the Contains predicate on the "failure_message" field.
func FailureMessageContains(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldContains(FieldFailureMessage, v))
}

// FailureMessageHasPrefix applies the HasPrefix predicate on the "failure_message" field.
func FailureMessageHasPrefix(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldHasPrefix(FieldFailureMessage, v))
}

// FailureMessageHasSuffix applies the HasSuffix predicate on the "failure_message" field.
func FailureMessageHasSuffix(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldHasSuffix(FieldFailureMessage, v))
}

// FailureMessageEqualFold applies the EqualFold predicate on the "failure_message" field.
func FailureMessageEqualFold(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEqualFold(FieldFailureMessage, v))
}

// FailureMessageContainsFold applies the ContainsFold predicate on the "failure_message" field.
func FailureMessageContainsFold(v string) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldContainsFold(FieldFailureMessage, v))
}

// DepartmentPagesEQ applies the EQ predicate on the "department_pages" field.
func DepartmentPagesEQ(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldDepartmentPages, v))
}

// DepartmentPagesNEQ applies the NEQ predicate on the "department_pages" field.
func DepartmentPagesNEQ(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNEQ(FieldDepartmentPages, v))
}

// DepartmentPagesIn applies the In predicate on the "department_pages" field.
func DepartmentPagesIn(vs ...int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldIn(FieldDepartmentPages, vs...))
}

// DepartmentPagesNotIn applies the NotIn predicate on the "department_pages" field.
func DepartmentPagesNotIn(vs ...int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNotIn(FieldDepartmentPages, vs...))
}

// DepartmentPagesGT applies the GT predicate on the "department_pages" field.
func DepartmentPagesGT(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGT(FieldDepartmentPages, v))
}

// DepartmentPagesGTE applies the GTE predicate on the "department_pages" field.
func DepartmentPagesGTE(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGTE(FieldDepartmentPages, v))
}

// DepartmentPagesLT applies the LT predicate on the "department_pages" field.
func DepartmentPagesLT(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLT(FieldDepartmentPages, v))
}

// DepartmentPagesLTE applies the LTE predicate on the "department_pages" field.
func DepartmentPagesLTE(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLTE(FieldDepartmentPages, v))
}

// UserPagesEQ applies the EQ predicate on the "user_pages" field.
func UserPagesEQ(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldUserPages, v))
}

// UserPagesNEQ applies the NEQ predicate on the "user_pages" field.
func UserPagesNEQ(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNEQ(FieldUserPages, v))
}

// UserPagesIn applies the In predicate on the "user_pages" field.
func UserPagesIn(vs ...int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldIn(FieldUserPages, vs...))
}

// UserPagesNotIn applies the NotIn predicate on the "user_pages" field.
func UserPagesNotIn(vs ...int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNotIn(FieldUserPages, vs...))
}

// UserPagesGT applies the GT predicate on the "user_pages" field.
func UserPagesGT(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGT(FieldUserPages, v))
}

// UserPagesGTE applies the GTE predicate on the "user_pages" field.
func UserPagesGTE(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGTE(FieldUserPages, v))
}

// UserPagesLT applies the LT predicate on the "user_pages" field.
func UserPagesLT(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLT(FieldUserPages, v))
}

// UserPagesLTE applies the LTE predicate on the "user_pages" field.
func UserPagesLTE(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLTE(FieldUserPages, v))
}

// DepartmentsUpsertedEQ applies the EQ predicate on the "departments_upserted" field.
func DepartmentsUpsertedEQ(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldDepartmentsUpserted, v))
}

// DepartmentsUpsertedNEQ applies the NEQ predicate on the "departments_upserted" field.
func DepartmentsUpsertedNEQ(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNEQ(FieldDepartmentsUpserted, v))
}

// DepartmentsUpsertedIn applies the In predicate on the "departments_upserted" field.
func DepartmentsUpsertedIn(vs ...int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldIn(FieldDepartmentsUpserted, vs...))
}

// DepartmentsUpsertedNotIn applies the NotIn predicate on the "departments_upserted" field.
func DepartmentsUpsertedNotIn(vs ...int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNotIn(FieldDepartmentsUpserted, vs...))
}

// DepartmentsUpsertedGT applies the GT predicate on the "departments_upserted" field.
func DepartmentsUpsertedGT(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGT(FieldDepartmentsUpserted, v))
}

// DepartmentsUpsertedGTE applies the GTE predicate on the "departments_upserted" field.
func DepartmentsUpsertedGTE(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGTE(FieldDepartmentsUpserted, v))
}

// DepartmentsUpsertedLT applies the LT predicate on the "departments_upserted" field.
func DepartmentsUpsertedLT(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLT(FieldDepartmentsUpserted, v))
}

// DepartmentsUpsertedLTE applies the LTE predicate on the "departments_upserted" field.
func DepartmentsUpsertedLTE(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLTE(FieldDepartmentsUpserted, v))
}

// UsersUpsertedEQ applies the EQ predicate on the "users_upserted" field.
func UsersUpsertedEQ(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldUsersUpserted, v))
}

// UsersUpsertedNEQ applies the NEQ predicate on the "users_upserted" field.
func UsersUpsertedNEQ(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNEQ(FieldUsersUpserted, v))
}

// UsersUpsertedIn applies the In predicate on the "users_upserted" field.
func UsersUpsertedIn(vs ...int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldIn(FieldUsersUpserted, vs...))
}

// UsersUpsertedNotIn applies the NotIn predicate on the "users_upserted" field.
func UsersUpsertedNotIn(vs ...int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNotIn(FieldUsersUpserted, vs...))
}

// UsersUpsertedGT applies the GT predicate on the "users_upserted" field.
func UsersUpsertedGT(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGT(FieldUsersUpserted, v))
}

// UsersUpsertedGTE applies the GTE predicate on the "users_upserted" field.
func UsersUpsertedGTE(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGTE(FieldUsersUpserted, v))
}

// UsersUpsertedLT applies the LT predicate on the "users_upserted" field.
func UsersUpsertedLT(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLT(FieldUsersUpserted, v))
}

// UsersUpsertedLTE applies the LTE predicate on the "users_upserted" field.
func UsersUpsertedLTE(v int) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLTE(FieldUsersUpserted, v))
}

// SyncedAtEQ applies the EQ predicate on the "synced_at" field.
func SyncedAtEQ(v time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldSyncedAt, v))
}

// SyncedAtNEQ applies the NEQ predicate on the "synced_at" field.
func SyncedAtNEQ(v time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNEQ(FieldSyncedAt, v))
}

// SyncedAtIn applies the In predicate on the "synced_at" field.
func SyncedAtIn(vs ...time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldIn(FieldSyncedAt, vs...))
}

// SyncedAtNotIn applies the NotIn predicate on the "synced_at" field.
func SyncedAtNotIn(vs ...time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNotIn(FieldSyncedAt, vs...))
}

// SyncedAtGT applies the GT predicate on the "synced_at" field.
func SyncedAtGT(v time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGT(FieldSyncedAt, v))
}

// SyncedAtGTE applies the GTE predicate on the "synced_at" field.
func SyncedAtGTE(v time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGTE(FieldSyncedAt, v))
}

// SyncedAtLT applies the LT predicate on the "synced_at" field.
func SyncedAtLT(v time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLT(FieldSyncedAt, v))
}

// SyncedAtLTE applies the LTE predicate on the "synced_at" field.
func SyncedAtLTE(v time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLTE(FieldSyncedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DirectorySyncRun) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DirectorySyncRun) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DirectorySyncRun) predicate.DirectorySyncRun {
	return predicate.DirectorySyncRun(sql.NotPredicates(p))
}
