#!/usr/bin/env bash
# Validate generated-file headers for committed generator outputs.

set -euo pipefail

cd "$(dirname "$0")/.."

failed=0
checked=0

optional_regular_file_present() {
  local file="$1"

  if ! reject_symlink_ancestors "$file"; then
    return 1
  fi
  if [[ -L "$file" ]]; then
    echo "[generated-headers] $file must be a regular file, not a symlink" >&2
    failed=1
    return 1
  fi
  if [[ ! -e "$file" ]]; then
    return 1
  fi
  if [[ ! -f "$file" ]]; then
    echo "[generated-headers] $file must be a regular file" >&2
    failed=1
    return 1
  fi
  return 0
}

optional_directory_present() {
  local dir="$1"

  if ! reject_symlink_ancestors "$dir"; then
    return 1
  fi
  if [[ -L "$dir" ]]; then
    echo "[generated-headers] $dir must be a directory, not a symlink" >&2
    failed=1
    return 1
  fi
  if [[ ! -e "$dir" ]]; then
    return 1
  fi
  if [[ ! -d "$dir" ]]; then
    echo "[generated-headers] $dir must be a directory" >&2
    failed=1
    return 1
  fi
  return 0
}

reject_symlink_ancestors() {
  local file="$1"
  local dir
  dir="$(dirname "$file")"

  while [[ "$dir" != "." && "$dir" != "/" ]]; do
    if [[ -L "$dir" ]]; then
      echo "[generated-headers] $file parent directory $dir must not be a symlink" >&2
      failed=1
      return 1
    fi
    if [[ -e "$dir" && ! -d "$dir" ]]; then
      echo "[generated-headers] $file parent path $dir must be a directory" >&2
      failed=1
      return 1
    fi
    if [[ ! -e "$dir" ]]; then
      return 0
    fi
    dir="$(dirname "$dir")"
  done
  return 0
}

check_first_line() {
  local file="$1"
  local expected="$2"

  if ! optional_regular_file_present "$file"; then
    return 0
  fi

  checked=$((checked + 1))
  local first_line
  IFS= read -r first_line < "$file" || first_line=""
  if [[ "$first_line" != "$expected" ]]; then
    echo "[generated-headers] $file missing expected generated header:" >&2
    echo "  expected first line: $expected" >&2
    failed=1
  fi
}

check_contains_near_top() {
  local file="$1"
  local marker="$2"

  if ! sed -n '1,8p' "$file" | grep -Fq "$marker"; then
    echo "[generated-headers] $file missing expected generated marker near top:" >&2
    echo "  expected marker: $marker" >&2
    failed=1
  fi
}

reject_ent_tree_symlinks() {
  local root="internal/persistence/ent"
  local symlinks=()

  if [[ -L "$root" ]]; then
    echo "[generated-headers] $root must be a directory, not a symlink" >&2
    failed=1
    return 1
  fi

  mapfile -t symlinks < <(find "$root" \
    ! -path "$root/schema" \
    ! -path "$root/schema/*" \
    ! -name 'generate.go' \
    -type l \
    | sort)

  for symlink in "${symlinks[@]}"; do
    echo "[generated-headers] $symlink must not be a symlink" >&2
    failed=1
  done
}

check_first_line "api/openapi.gen.go" "// Code generated by oapi-codegen; DO NOT EDIT."

if optional_directory_present "internal/persistence/ent"; then
  if reject_ent_tree_symlinks; then
    mapfile -t ent_files < <(find internal/persistence/ent \
      -name '*.go' \
      ! -path 'internal/persistence/ent/schema/*' \
      ! -name 'generate.go' \
      ! -type l \
      | sort)

    for ent_file in "${ent_files[@]}"; do
      check_first_line "$ent_file" "// Code generated by ent, DO NOT EDIT."
    done
  fi
fi

if optional_regular_file_present "web/src/lib/api/openapi.ts"; then
  checked=$((checked + 1))
  check_contains_near_top "web/src/lib/api/openapi.ts" "This file was auto-generated by openapi-typescript."
  check_contains_near_top "web/src/lib/api/openapi.ts" "Do not make direct changes to the file."
fi

if [[ $failed -ne 0 ]]; then
  echo "" >&2
  echo "Fix: regenerate the affected file instead of hand-editing or replacing the generated header." >&2
  exit 1
fi

if [[ $checked -eq 0 ]]; then
  echo "[generated-headers] no generated files found; skipping."
  exit 0
fi

echo "[generated-headers] OK ($checked files checked)"
