package main

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestDCOSignoffEmailMustMatchAuthorEmail(t *testing.T) {
	tests := []struct {
		name        string
		authorEmail string
		body        string
		wantOK      bool
		want        []string
	}{
		{
			name:        "matching author email",
			authorEmail: "author@example.com",
			body:        "Signed-off-by: Author <AUTHOR@example.com>",
			wantOK:      true,
			want:        []string{"[dco-check] OK"},
		},
		{
			name:        "mismatched signoff email",
			authorEmail: "author@example.com",
			body:        "Signed-off-by: Other <other@example.com>",
			want: []string{
				"Signed-off-by email does not match commit author email",
				"sign-off email(s): other@example.com",
			},
		},
		{
			name:        "missing signoff",
			authorEmail: "author@example.com",
			body:        "",
			want:        []string{"missing Signed-off-by trailer"},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			root := newDCORepo(t)
			base := dcoCommit(t, root, "base.txt", "base\n", "base@example.com", "Signed-off-by: Base <base@example.com>")
			head := dcoCommit(t, root, "head.txt", tc.name+"\n", tc.authorEmail, tc.body)

			out, err := runDCOCheck(t, root, map[string]string{
				"DCO_BASE_REF": base,
				"DCO_HEAD_SHA": head,
			})
			if tc.wantOK && err != nil {
				t.Fatalf("dco check failed: %v\n%s", err, out)
			}
			if !tc.wantOK && err == nil {
				t.Fatalf("dco check passed unexpectedly:\n%s", out)
			}
			for _, want := range tc.want {
				if !strings.Contains(out, want) {
					t.Fatalf("dco output = %q, want substring %q", out, want)
				}
			}
		})
	}
}

func TestDCOFallbackWithoutUpstreamValidatesHead(t *testing.T) {
	root := newDCORepo(t)
	dcoCommit(t, root, "head.txt", "head\n", "author@example.com", "")

	out, err := runDCOCheck(t, root, nil)
	if err == nil {
		t.Fatalf("dco check passed unexpectedly:\n%s", out)
	}
	if !strings.Contains(out, "missing Signed-off-by trailer") {
		t.Fatalf("dco output = %q, want missing signoff", out)
	}
}

func TestDCORejectsAIToolBranding(t *testing.T) {
	tests := []struct {
		name string
		body string
		want string
	}{
		{
			name: "generated by trailer",
			body: "Signed-off-by: Author <author@example.com>\n\nGenerated-by: Claude",
			want: "Generated-by: Claude",
		},
		{
			name: "coauthored by ai tool",
			body: "Signed-off-by: Author <author@example.com>\n\nCo-authored-by: Claude <noreply@example.com>",
			want: "Co-authored-by: Claude",
		},
		{
			name: "model name in message",
			body: "Signed-off-by: Author <author@example.com>\n\nPrompt upgraded with gpt-5.1 output.",
			want: "gpt-5.1",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			root := newDCORepo(t)
			base := dcoCommit(t, root, "base.txt", "base\n", "base@example.com", "Signed-off-by: Base <base@example.com>")
			head := dcoCommit(t, root, "head.txt", tc.name+"\n", "author@example.com", tc.body)

			out, err := runDCOCheck(t, root, map[string]string{
				"DCO_BASE_REF": base,
				"DCO_HEAD_SHA": head,
			})
			if err == nil {
				t.Fatalf("dco check passed unexpectedly:\n%s", out)
			}
			for _, want := range []string{
				"commit message contains AI tool branding",
				tc.want,
				"contain AI tool branding",
			} {
				if !strings.Contains(out, want) {
					t.Fatalf("dco output = %q, want substring %q", out, want)
				}
			}
		})
	}
}

func newDCORepo(t *testing.T) string {
	t.Helper()

	root := t.TempDir()
	dcoWriteFile(t, root, "scripts/check_dco_signoff.sh", dcoScript(t), 0o750)
	gitCommand(t, root, nil, "init")
	gitCommand(t, root, nil, "config", "commit.gpgsign", "false")
	return root
}

func dcoScript(t *testing.T) string {
	t.Helper()
	raw, err := os.ReadFile("check_dco_signoff.sh")
	if err != nil {
		t.Fatalf("read DCO script: %v", err)
	}
	return string(raw)
}

func dcoCommit(t *testing.T, root, name, body, authorEmail, signoff string) string {
	t.Helper()
	dcoWriteFile(t, root, name, body, 0o644)
	gitCommand(t, root, nil, "add", ".")
	args := []string{"commit", "-m", "test commit"}
	if signoff != "" {
		args = append(args, "-m", signoff)
	}
	env := map[string]string{
		"GIT_AUTHOR_NAME":     "Test Author",
		"GIT_AUTHOR_EMAIL":    authorEmail,
		"GIT_COMMITTER_NAME":  "Test Committer",
		"GIT_COMMITTER_EMAIL": "committer@example.com",
	}
	gitCommand(t, root, env, args...)
	return strings.TrimSpace(gitCommand(t, root, nil, "rev-parse", "HEAD"))
}

func dcoWriteFile(t *testing.T, root, name, body string, mode os.FileMode) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(name))
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		t.Fatalf("mkdir %s: %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(body), mode); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func runDCOCheck(t *testing.T, root string, env map[string]string) (string, error) {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, "bash", "scripts/check_dco_signoff.sh")
	cmd.Dir = root
	cmd.Env = os.Environ()
	for key, value := range env {
		cmd.Env = append(cmd.Env, key+"="+value)
	}
	raw, err := cmd.CombinedOutput()
	return string(raw), err
}

func gitCommand(t *testing.T, root string, env map[string]string, args ...string) string {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	// #nosec G204 -- tests invoke git with helper-owned arguments against
	// temporary repositories only.
	cmd := exec.CommandContext(ctx, "git", args...)
	cmd.Dir = root
	cmd.Env = os.Environ()
	for key, value := range env {
		cmd.Env = append(cmd.Env, key+"="+value)
	}
	raw, err := cmd.CombinedOutput()
	out := string(raw)
	if err != nil {
		t.Fatalf("git %s failed: %v\n%s", strings.Join(args, " "), err, out)
	}
	return out
}
