-- Create "report_notification_deliveries" table
CREATE TABLE "report_notification_deliveries" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "idempotency_key" character varying NOT NULL,
  "provider_message_id" character varying NULL,
  "provider_status" character varying NULL,
  "status" character varying NOT NULL DEFAULT 'pending',
  "raw" jsonb NOT NULL,
  "failure_reason" character varying NULL,
  "delivered_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "final_report_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "report_notification_deliveries_final_reports_notification_deliv" FOREIGN KEY ("final_report_id") REFERENCES "final_reports" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "report_notification_deliveries_idempotency_key_key" to table: "report_notification_deliveries"
CREATE UNIQUE INDEX "report_notification_deliveries_idempotency_key_key" ON "report_notification_deliveries" ("idempotency_key");
-- Create index "reportnotificationdelivery_final_report_id_created_at" to table: "report_notification_deliveries"
CREATE INDEX "reportnotificationdelivery_final_report_id_created_at" ON "report_notification_deliveries" ("final_report_id", "created_at");
-- Create index "reportnotificationdelivery_status_updated_at" to table: "report_notification_deliveries"
CREATE INDEX "reportnotificationdelivery_status_updated_at" ON "report_notification_deliveries" ("status", "updated_at");
