-- Create "diagnosis_tool_templates" table
CREATE TABLE "diagnosis_tool_templates" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "alert_source_profile_id" bigint NOT NULL,
  "tool" character varying NOT NULL,
  "query_template" text NULL,
  "default_limit" bigint NOT NULL,
  "default_window_ns" bigint NOT NULL,
  "max_window_ns" bigint NOT NULL,
  "default_step_ns" bigint NOT NULL,
  "enabled" boolean NOT NULL DEFAULT false,
  "enabled_at" timestamptz NULL,
  "disabled_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "diagnosis_tool_templates_name_key" to table: "diagnosis_tool_templates"
CREATE UNIQUE INDEX "diagnosis_tool_templates_name_key" ON "diagnosis_tool_templates" ("name");
-- Create index "diagnosistooltemplate_alert_source_profile_id_tool_enabled" to table: "diagnosis_tool_templates"
CREATE INDEX "diagnosistooltemplate_alert_source_profile_id_tool_enabled" ON "diagnosis_tool_templates" ("alert_source_profile_id", "tool", "enabled");
-- Create index "diagnosistooltemplate_enabled_updated_at" to table: "diagnosis_tool_templates"
CREATE INDEX "diagnosistooltemplate_enabled_updated_at" ON "diagnosis_tool_templates" ("enabled", "updated_at");
