-- Create "report_workflow_policies" table
CREATE TABLE "report_workflow_policies" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "alert_source_profile_id" bigint NOT NULL,
  "grouping_policy_id" bigint NOT NULL,
  "trigger_mode" character varying NOT NULL DEFAULT 'manual_replay',
  "report_scenario" character varying NOT NULL DEFAULT 'single_alert',
  "diagnosis_follow_up" character varying NOT NULL DEFAULT 'disabled',
  "enabled" boolean NOT NULL DEFAULT false,
  "enabled_at" timestamptz NULL,
  "disabled_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "report_workflow_policies_name_key" to table: "report_workflow_policies"
CREATE UNIQUE INDEX "report_workflow_policies_name_key" ON "report_workflow_policies" ("name");
-- Create index "reportworkflowpolicy_alert_source_profile_id_grouping_policy_id" to table: "report_workflow_policies"
CREATE INDEX "reportworkflowpolicy_alert_source_profile_id_grouping_policy_id" ON "report_workflow_policies" ("alert_source_profile_id", "grouping_policy_id");
-- Create index "reportworkflowpolicy_enabled_updated_at" to table: "report_workflow_policies"
CREATE INDEX "reportworkflowpolicy_enabled_updated_at" ON "report_workflow_policies" ("enabled", "updated_at");
